### ISSUE TITLE
[1.0.0.12][Improvement] The new moving platform system placing is wonky.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#100]
When you try to place the moving platform in a level, you never end up placing all nessesary objects in the same place as you had your mouse pointer hovered.

This creates situations when user needs to guess if the platform will be placed in the desired place.

**Comment by whitelilydragon** [comment]
I have changed the bug class to Class D, because the drawn path is still correct before and after placement of a tile, it's just that the preview sprite was drawn 5 pixels higher up, and 4 pixels farther back than it should have been.

But it is fixed now!
