### ISSUE TITLE
[1.0.1.14][Normal] Improvements and bugfixes for the automatic moving platform feature.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#101]
Bugs, UX and QoL suggestions for the new moving platform system.

- The Platform Type Selection popup z-index is pretty low, making it hidden under normal tiles and not clickable until you remove the tile over it. I believe popup should be on the upmost layer.
- The area of where the popup shows up is quite large making it hard to place items around it. See Screenshot 1.
- There is something weird when it comes to platform's properties on reloads. Sometimes, it can grab items or enemies previously not in the range of the platform. It can also sometimes grab crystals and unique enemies which I'm not sure are supposed to be carried.
- For the strange re-arrangement on reloads: I have something like this in Screenshot 2. I have no idea how to reproduce it or how it happened.
- I still believe the act of placing those platforms could get some improvements. I mentioned that sometimes the line you draw while drag and dropping a new platform is not representative of the platform that will be placed. That means there is a lot of "oh crap, I need to delete it and place it again". That however, leaves a lot of "Platform movement change" tiles that litter the area (UPDATE: It looks like horizonal platforms are only affected. Vertical delete fine). This feature is great, but I believe it needs a future rework when it comes to usability in practice.

![S1](https://user-images.githubusercontent.com/7067769/107117141-6f716a00-6878-11eb-93ff-96ebc3e0e3bd.png)
![LaWut2](https://user-images.githubusercontent.com/7067769/107117142-713b2d80-6878-11eb-9912-b4247549315a.gif)
![image](https://user-images.githubusercontent.com/7067769/107117138-6aacb600-6878-11eb-97d2-da5fe5703496.png)

Placement issues:
![Placement issue](https://user-images.githubusercontent.com/7067769/107126048-ccd3de00-68ad-11eb-8aa0-2d623c94277b.gif)
Line drawn is inconsistent with line placed.
Markers placements are different between when you started dragging, during dragging and after dropping.

**Comment by whitelilydragon** [comment]
I finally took a deeper look at these issues, and addressed them as best I could! I even found a lot of other misc issues around floating platforms that I was able to fix, both with the core collision system's handling of floating platforms, as well as the gimmicks' end of things.

Here's a peak of our most recent rolling build's changelog!

```
Adjustments
---

-Removed all error messages related to "Cannot interact with special object flag tiles", because they are never visible anyway. It has proven more of an annoyance than a help with the stage building experience
-Disabled interactions with the "FOF" tile layer entirely, including the FOF tile layer scanner
    -It's no longer a relavant tile layer to the end-user, now that moving platform objects have long-since been taking care of this interaction for them.
    -All floating platform tiles in the tile menu no longer set your default layer to the FOF layer, either, now that it's shown to be more important that stand-alone floating platforms belong on the slope layer; all floating platform objects can spawn, then control, any moving platforms they create
-Floating platform popups now have an X icon on their top-right corners!
-All circular pendalum platforms now change their floating platforms based on your current background!

Bugfixes
---

-Removed more "dirty" tile-existence checks from the horizontal and vertical platform gimmicks
-Finally fixed a bug where horizontal and vertical platforms wouldn't delete their "reverse course" tiles after being deleted themselves. They can now do this. (Within reason)
    -Note, this only applies if the platforms were capable of drawing a path; if distances between moving platforms and their "reverse course" tiles are too great, they won't be capable of drawing a path, or finding, then storing the IDs of those tiles
-All moving platform gimmicks can no longer capture random objects, only enemies
-Removed yet more ugly sidebar checks for the editor, which should make its click interactions with tiles nearby the sidebar more consistent, whether the editor's side bar is slid away or not
-Items that are allowed to draw over gimmick objects, were still drawing underneath the sidebar while held by the cursor
-Floating platforms now perform tile-existence checks before drawing tiles
-Floating platforms no longer draw their popup graphics while the mouse is over the editor's sidebar, or if the tile menu was invoked via keyboard shortcuts, while the mouse was hoving over them
-Floating platforms no longer reset their positions while the mouse is hovering over them, over the editor's sidebar
-More tile-existence safety checks for the floating platform gimmicks
-No more camera jittering each time you land on floating platforms
-The floating platforms themselves are no longer sending their coordinates to the player object for pixel-precise collisions (the player is now figuring that out on their own!)
-Floating platforms now have their platforms drawn over their in-game tiles, so nothing on tile layers can draw over them anymore
-No more tile scanner that's looking for floating platform tiles every frame, which should also mean lots of micro-optimizations for the player object's most frequent conditional collision checks
-Horizontal and vertical platforms didn't have an up-to-date list of backgrounds to automatically detect
-The new click-drag delete tool wasn't scanning for exceptional tiles before deleting them, causing all kinds of problems for floating platforms especially
```

All I really have left at this point are to address the line-drawing alignment issues, but everything should have been alleviated and then some. Thank you for reporting!
