### ISSUE TITLE
[1.0.0.14][Minor] Flower Bomb not found error in Play Mode

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#103]
![Issue](https://user-images.githubusercontent.com/7067769/107146477-e0805280-6948-11eb-93fd-0e04db6abe76.png)

If you stack boxes on top of bombs and they set everything exploding, few seconds after everything blows up and crystals drop, this error can be seen. I doesn't break the game and there are no more negative effects, but it's strange this showed up. This can be reproduced fairly consistently

**Comment by whitelilydragon** [comment]
All I've done for now is simply disable the error message, because it was only useful for debugging purposes when I composed that error message anyway. I may re-enable in future builds if I can figure out how (and why) it's spitting out errors erroneously.
