### ISSUE TITLE
SMA doesn't open

### ISSUE THREAD

**Issue by DudinkaSan** [whitelilydragon/ShangMuArchitect#104]
Hello, It feels nice to contribute to the game. However the game haven't opened in my PC, it gives an error, more specifically:
"Windows cannot access the device, directory or especified file. Maybe you don't have the correct permissions to access the item. (roughly translated from portuguese)" and it doesn't open. I don't know if there is an issue with the file itself, or the game, or my PC, but I really want to help this game grow.

**Comment by whitelilydragon** [comment]
We discussed this off GitHub, and the reporter of the post has got the fan game to run! It was likely a lot of things:

- Anti-viruses can block the binary from executing, so the fan game needs to be added to the exceptions list of the related anti-virus software
- Downloaded files sometimes need to be "unblocked" in their properties window, before they could be executed
- Windows SmartScreen causes issues with the installer package for the fan game. (But not the portable package.)

Thank you for reporting!
