### ISSUE TITLE
Collision Bug

### ISSUE THREAD

**Issue by DudinkaSan** [whitelilydragon/ShangMuArchitect#105]
Map: Bouncy laucher
Bug: Collision on the ground
How to recreate: Nearby the location on the image file, jump on the upper part of the ramp, keep pressing left and you will fall to the ground, keep pressing even further and you can fall even more.
![smabug](https://user-images.githubusercontent.com/77648014/107453703-3a8c3e00-6b2a-11eb-918f-a6742f9d756b.png)
Check if it happens

**Comment by whitelilydragon** [comment]
This is now fixed as a result of a new update that was just released!

Thank you for reporting!
