### ISSUE TITLE
[1.0.0.15][Release](UI Issue) Game Resolution resets when AlternateSyncMethod is enabled

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#106]
Upon bootup, SMA resets to the "x1" resolution. This regression also occurs whenever the "AlternateSyncMethod" is enabled via pressing F8.

**Comment by whitelilydragon** [comment]
I have moved the code for adjusting the window's size and position after the Windows 10 check *and* VSYNC check in the game's startup code, so this shouldn't happen again.

I can't check this myself for not having hardware affected by Game Maker's default VYSNC method, so please report back with the next build upload if this issue persists!

**Comment by Deckardsmegson** [comment]
This issue still persists as of version 1.0.0.20
Pressing F8 to enable the method ingame still resets the resolution to x2

**Comment by whitelilydragon** [comment]
Because alt sync support is being removed from the game, (we no longer need it!) I'm closing this ticket!
