### ISSUE TITLE
[1.0.0.15][Release][Milla] Supershieldburst Recoil Accuracy

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#107]
From a Standstill: 	In FP1 while standing, Milla slides about 16~24px to the opposite direction that the SSB has been fired at.
                                This applies if fired diagonally upward, too. Milla comes to a complete standstill.
			        In SMA, Milla Slides about 2-3 times as far (entering her running "dog" animation). 
                                It feels like she is walking on ice.

Moving forward: 	Same as above. Milla comes to a standstill and only starts moving after the SSB particles are gone.
			        In SMA, Milla slides further away and is able to summon a Cube before all particles are gone.
                                Since she does not come to a standstill, she keeps her walking cycle.

https://user-images.githubusercontent.com/69774625/107865370-d3da8d80-6e65-11eb-9f5e-cfaf5b53bb86.mp4

https://user-images.githubusercontent.com/69774625/107865371-d5a45100-6e65-11eb-87ff-44e782face8f.mp4

https://user-images.githubusercontent.com/69774625/107865373-d806ab00-6e65-11eb-9a6b-3f46df5ecce1.mp4

https://user-images.githubusercontent.com/69774625/107865374-d937d800-6e65-11eb-9620-734f47d11802.mp4

**Comment by whitelilydragon** [comment]
>In FP1 while standing, Milla slides about 16~24px to the opposite direction that the SSB has been fired at.

From what I've observed via screenshot overlays, it seems to be about ~40 pixels, when she's sliding backwards.

I'll report back once I have a fix, Milla's code is proving to obtuse, as usual.

![image](https://user-images.githubusercontent.com/23007238/107977423-15b02480-6f89-11eb-87cb-70a5f61eb62f.png)

**Comment by whitelilydragon** [comment]
I was able to fix this with a friction speed override specifically for Milla's super shield bursts! Her friction speed is simply higher than normal when sliding backwards after recoiling from a super shield burst: 0.5 vs 0.56875, and it makes all of the difference!

Thank you for reporting!
