### ISSUE TITLE
[1.0.0.15][Release] (Audio) Death Soundeffect is 3-4 times louder at 10% Sound volume 

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#108]
https://cdn.discordapp.com/attachments/739994967186997329/810255676063744030/Screenshot_2021-02-13_220638.png

As seen in the Audio-Visualizer, the "Death-cry" is a lot louder and not properly balanced. It pierces speakers quite badly, too.

**Comment by whitelilydragon** [comment]
This was an oversight in the game's scripts for adjusting the in-game volumes of sound effects! After I added the characters' death screams to those scripts, they're not screaming louder than anything else *bricked*

Thank you for reporting!
