### ISSUE TITLE
[1-17-6-7-4][Minor] Removing Crystal Flower with animation leaves undeletable element behind

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#11]
![image](https://user-images.githubusercontent.com/7067769/90954441-9d065a80-e474-11ea-9955-eebc219a4c28.png)

**Comment by NBlastMax** [comment]
Downgraded to minor. Cannot reproduce the issue.

**Comment by whitelilydragon** [comment]
This was fixed in a previous build! I hadn't noticed this happening myself, thank you for reporting!
