### ISSUE TITLE
Super shield burst works funny with ladders

### ISSUE THREAD

**Issue by TreyLina** [whitelilydragon/ShangMuArchitect#110]
If you super shield burst into a ladder vertically - then hold up, you get sent flying upwards. The closer you do the super shield burst to the ground, the more you get pushed upwards from climbing off the ladder.

**Comment by whitelilydragon** [comment]
This is an interesting! I was able to fix it by having Milla's ladder code keep her "rocket dog" speed variable reset.

Thank you for reporting! I'm glad you caught this, this is very out-of-the-ordinary!
