### ISSUE TITLE
Getting hurt is too floaty and momentum resetting

### ISSUE THREAD

**Issue by TreyLina** [whitelilydragon/ShangMuArchitect#112]
In the original game - if you got hurt, your momentum isn't completely dead, but is retained partially. You also have no control over your trajectory in this state. I also don't believe you get pushed up at all in this state either, if not very little. (correct me if I'm wrong. I haven't played the OG FP in ages...).

This actually matters quite a bit in speedrunning, it makes the flow less disrupted while you go fast along the way, especially as Milla. In niche cases, it can be used as a damage boost too.

**Comment by whitelilydragon** [comment]
Damage boosting both horizontally and vertically is a thing, so how far up you bounce depends on your remaining jump speed before you were hurt.

And that's true, your horizontal momentum is traded down to a lower value based on some factors.

https://user-images.githubusercontent.com/23007238/107984145-4ac27400-6f95-11eb-955b-a0c81753cf50.mov

I had the correct formulas that Tris provided me, but how I was implementing them wasn't correct, based on your report. I have adjusted the conditions for damage boosting and also disabled horizontal controls during the hurt state. I won't close the ticket until we're sure this behavior is correct
