### ISSUE TITLE
[1.0.0.16] Lilac cannot Dragon Boost out of a Dive Kick

### ISSUE THREAD

**Issue by NitroSplint** [whitelilydragon/ShangMuArchitect#114]
In Freedom Planet, Lilac can Dragon Boost out of a Dive Kick.
This is currently not possible in Shang Mu Architect.

**Comment by whitelilydragon** [comment]
I'm glad you noticed, but I've never thought to try that myself!

This was a super easy fix, all I had to do was disable checking against the dive-kick animation for the dragon boost- Basically, I had too many checks in the dragon boost's code *bricked*

Thank you for reporting!
