### ISSUE TITLE
[1.0.0.16] Lilac's Uppercut cuts off if the Jump Button is held going up

### ISSUE THREAD

**Issue by NitroSplint** [whitelilydragon/ShangMuArchitect#116]
When performing an Uppercut, if the Jump Button is held during the ascent, Lilac stops after a certain point midair and drops. It's close to the apex of the move.

This does not happen in Freedom Planet. Holding the Jump Button there has no effect.

**Comment by whitelilydragon** [comment]
As a consequence of how I fixed https://github.com/whitelilydragon/ShangMuArchitect/issues/115#issue-809654097, it no longer has a jarring stopping point while holding the jump button!

Thank you for reporting!
