### ISSUE TITLE
[1.0.0.16] Lilac's Down-Up Cyclone does not work

### ISSUE THREAD

**Issue by NitroSplint** [whitelilydragon/ShangMuArchitect#117]
The Down-Up Cyclone is a move that's performed by doing a Down Air Cyclone (which is done by hitting Jump while holding Down midair) and then immediately holding Up. This increases Lilac's airtime during the Air Cyclone, which makes a large difference when moving horizontally using the move.

This does not work in Shang Mu Architect. Down-Neutral Cyclone and Down-Down Cyclone (which reduces Lilac's airtime) both work, but not Down-Up Cyclone.

**Comment by whitelilydragon** [comment]
I fixed this by appending a new line of code to readjust the gravity speed and gravity acceleration parameter during the cyclone phase itself, by pressing Up. This is something I had never known Lilac could do, so this is surprising!

Thank you for reporting!
