### ISSUE TITLE
[1.0.0.17] Lilac's High Uppercut goes too high

### ISSUE THREAD

**Issue by NitroSplint** [whitelilydragon/ShangMuArchitect#118]
The High Uppercut is that move referred to as "Lilac's glitch jump" in `FP Accuracy.txt`. I used the same testing areas mentioned in #115 for this. (The start of Fortune Night for FP, and the block to the left at the start of `BouncyLauncher.map` for SMA.)

In Freedom Planet, Lilac covers a maximum of **165** and a minimum to **145** vertical units using the move. Indeed, this is not consistent. Her y-position goes from 522 to 357 and 377 respectively. Several attempts also resulted in 160, 155 and 150 units, with the occasional +1/-1 unit on some.

In Shang Mu Architect, Lilac currently covers **216** vertical units using the move. Her y-position goes from 2080 to 1864 (rounded down).

**Comment by whitelilydragon** [comment]
I also hadn't realized that was still too high, whoopsie! o ^ o

I was able to fix this by adjusting the parameter for glitch jumping from -3.25, to -2, which grants 166.53 pixels of height. (Which is close enough.) Basically, the glitch jump appends extra height to the initial jump, so -7 goes to -9.

Thank you for reporting!
