### ISSUE TITLE
[1-17-6-7-4][Major] Petals aren't collected while playing levels and running upside down

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#12]
![Showcase](https://user-images.githubusercontent.com/7067769/90974802-b7047380-e52e-11ea-8867-afc49edf5b3e.gif)

**Comment by whitelilydragon** [comment]
Closing this ticket, because the issue has been fixed for both floating petals _and_ gems. All I had to do was check for the player's central X/Y coordinates, instead of their feet's X/Y position.

Thanks for reporting, I missed this one!
