### ISSUE TITLE
[1.0.0.18][QOL] Game crash when out of focus/clicked into focus during loading sequences

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#121]
It crashes, but it's probably your fault. I mean, the game is loading. What are you doing looking at other things during a two second sequence?

![image](https://user-images.githubusercontent.com/69790793/108450415-098ec600-721a-11eb-8674-9c8b8f29639c.png)

**Comment by whitelilydragon** [comment]
Yes, this is on a level that I can't necessarily fix- not without turning the loading loop into an iterative **if** statement, or a loop that runs for 16 iterations, lets a 1/60 of a second pass, (or one in-game frame) then continues the next 16 stage data entries in the map file- just to prevent the game's window from appearing to "freeze" as it does during longer levels.

But, this would make longer levels take entire minutes to load, so, I'm at a loss for solutions here
