### ISSUE TITLE
[1.0.0.18][Extremely Minor (Accuracy Issue)] Screen wipe transition slower than the original

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#122]
Something I've always noticed was that the screen wipe animation was just the slightest bit slower than it was in FP. It might just be the game running slower on my PC? But I've tried it on two different devices and I'm still noticing it.

I don't have the tools to do a side-by-side right now, but I hope someone else can if it's an issue for not just me-
https://user-images.githubusercontent.com/69790793/108451605-f67cf580-721b-11eb-9506-6cb66b58bc98.mp4
https://user-images.githubusercontent.com/69790793/108451609-f7ae2280-721b-11eb-82c9-e195f11fc736.mp4

**Comment by benjistring** [comment]
[ADDENDUM] - This is not about loading times!!! It's on how fast the black bar on the screen swipes across

**Comment by whitelilydragon** [comment]
I'm amazed that there was a difference in speeds at all! o ^ o After double-checking the original game, the transition was happening at 31 pixels per frame, whereas I had it set to 23.67 pixels per frame! That's quite a difference!

Thank you for reporting!
