### ISSUE TITLE
[1.0.0.18][Minor] Water UI appears for brief moment if game is stopped in the editor while underwater, and resumed on land

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#125]
https://user-images.githubusercontent.com/69790793/108454535-69d53600-7221-11eb-942d-35bce85b1c71.mp4

**Comment by benjistring** [comment]
The same issue happens if you exit a level while you're underwater, and play another one that starts on land.

**Comment by whitelilydragon** [comment]
This was a pretty easy fix, but still a huge oversight! Now, the breath bar doesn't draw while in editor mode, (Drawing over the debug HUD is a bad position; I should design a new breath bar just for editor mode.) and I've reset the breath bar's drawn offset with each room start!

Thank you for reporting!
