### ISSUE TITLE
[1.0.0.18][VERY Minor] Using the "switch character" button in the menu swaps the character sprite for about a millisecond on character specific levels

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#129]
This one is self explanatory but it's not really a game breaking issue. Just something I noticed when I spammed the buttons!
[Also a suggestion] - Turn off the swap character sound for those levels too

**Comment by whitelilydragon** [comment]
Simply checking if the allowed characters for a stage was set to "All" prevented this issue entirely- as well as the noises ^ v ^

Thank you for reporting!
