### ISSUE TITLE
[1-17-6-7-4][Major] Backdrop indefinitely set to menu screen after playing a level, then resizing the game.

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#13]
![image](https://user-images.githubusercontent.com/69790793/90975651-ff9a3d80-e4ea-11ea-9535-d54954824275.png)

This is easiest to recreate going into a level with 2x screen, which is the default, backing out, going into 1x, and entering any kind of menu afterwards.

**Comment by whitelilydragon** [comment]
It's a little more difficult than that to reproduce the issue, I only got it to happen once; every other time, the game crashed after so many attempts at entering/exiting levels while hammering different window resolutions with the function keys.

My theory is that the inputs for the start button weren't strict enough, so I've battened it down a bit better, with stricter checks before opening the pause menu. I can't seem to recreate the issue; let me know how that goes in the next nightly build!
