### ISSUE TITLE
[1.0.0.18][Minor] Getting hit by DNA cannon's beam on a ladder can send you in the wrong direction, and it won't knock you off the first time, making characters cling to ladders incorrectly

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#130]
https://user-images.githubusercontent.com/69790793/108457495-9ab86980-7227-11eb-8071-2197f8dd36ee.mp4

**Comment by whitelilydragon** [comment]
Fixing this was fortunately as simple as disabling the ladder state if you're getting hurt! Now, characters will fall off of ladders *and* hangbars if they're hurt.

Thank you for reporting!
