### ISSUE TITLE
[1.0.0.18][Minor] Ladders that are placed halfway in the ground do not function properly

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#131]
https://user-images.githubusercontent.com/69790793/108458101-c6881f00-7228-11eb-8720-5eec4fd0629e.mp4

**Comment by whitelilydragon** [comment]
I addressed this by having some code added to the upwards moving code block for ladders, that pushes the player up by 1 pixel until they've cleanly exited the ground; this fortunately has no affect on how ladder climbing interacts with anything else.

Thank you for reporting!
