### ISSUE TITLE
[1.0.0.18][Minor] Encourage holding right click to delete objects - Certain objects (like spiked balls) don't respond to singular clicks as well as others with larger hitboxes

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#132]
what a title D:
 sometimes deleting items just flat out doesn't work for me if I do a single click - I have to move my mouse around a bit

**Comment by whitelilydragon** [comment]
I have refactored how deleting things work for the first time in years! Now, there's a click-drag selection box for deleting things, as well as the traditional "delete in one click" option!

Simply hold right-click with the mouse, then drag a selection up to 512 pixels, that will delete everything within the selection box. (Or only on your selected layer in manual mode.)

The delete function also had a lot of dirty tile-existence checks, so its behavior should be a lot more consistent in general. Thank you for reporting!
