### ISSUE TITLE
[1.0.0.18][VERY Minor] Clicking and moving already placed springs in the editor has an extremely low chance of occurring because of close proximity to the directional drag buttons

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#134]
![image](https://user-images.githubusercontent.com/69790793/108460052-ace8d680-722c-11eb-9199-bf0b18b96238.png)
Even at the highest zoom level, I'm having particular difficultly clicking and dragging already placed springs to a different location.
Very, very small issue.

**Comment by whitelilydragon** [comment]
Closing this ticket now that springs are objects, and are no longer tileable assets!
