### ISSUE TITLE
[1.0.0.18][Minor] Users can spam the QUIT menu button

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#138]
This one's funny :P

https://user-images.githubusercontent.com/69790793/108468068-07892f00-723b-11eb-82e8-8eec0047df2b.mp4

**Comment by whitelilydragon** [comment]
I can't believe I had never checked this! It's an easy fix, at least, I was able to fix it by having it check against the activation of the transition itself.

Thank you for reporting!
