### ISSUE TITLE
[1.0.0.18][Minor] Lilac gets stuck in a running animation after holding down while dragonboosting from a slope into a wall 

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#139]
https://user-images.githubusercontent.com/69790793/108468986-60a59280-723c-11eb-8d4e-0d1ef332194a.mp4

**Comment by whitelilydragon** [comment]
This is a general character movement issue, it's not exclusive to Lilac! She's just the one where it is most obvious.

So, I've fixed it by changing the conditions for the wall pushing animation; it triggers at 0 degrees, but if you're at a non-zero angle, it resets to the standing animation; pushing against a wall at an angle just looks too funny, omg

Thank you for reporting! ^ v ^
