### ISSUE TITLE
[1-17-6-7-4][Improvement]: Give the .exe publisher metadata so the game isn't blocked by SmartScreen or other default antiviruses

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#14]
A lot of fangames haven't done this, not sure why. D:

**Comment by whitelilydragon** [comment]
I'm having trouble researching what publisher metadata is. Could you elaborate on that? This is the extent of publishing that I can see on Game Maker, unless there's something I'm missing

![image](https://user-images.githubusercontent.com/23007238/91382785-7b9cca00-e7f8-11ea-89f6-156f50e8262a.png)

**Comment by whitelilydragon** [comment]
I'm closing this ticket, because no explanation is on offer, and all of the research I've done is unhelpfully vague!

I will do something about this if I can learn what publisher metadata means within context of a executable binary, but all I'm able to find has to do with web services.
