### ISSUE TITLE
[1.0.0.18][Accuracy issue] Milla should pause her digging after not finding anything in the ground

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#140]
They give you a little moment to process that whimper in the og game ;-;

I think there's also an animation issue as well. If you keep spamming the dig, sometimes Milla's sprite will flash to standing. If you have trouble seeing it, let me know and I can send a video!

**Comment by whitelilydragon** [comment]
This was done intentionally to avoid pacing issues. The speed at which you dig for goodies in FP1 simply wouldn't work within the context of Shang Mu Architect.
