### ISSUE TITLE
[1.0.0.18]{QOL][Accuracy issue] Milla should stand in front of all the holes she's dug except the latest one

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#141]
![image](https://user-images.githubusercontent.com/69790793/108469731-a9118000-723d-11eb-984e-98c5cef578e3.png)

![image](https://user-images.githubusercontent.com/69790793/108470107-48367780-723e-11eb-90c2-c91be9a6a102.png)
This becomes especially apparent when her feet begin to peep out lower than the hole sprites while walking and it makes it easier to see what you're digging!

**Comment by whitelilydragon** [comment]
I can't rectify depth changes for tiles that Milla had previously spawned, (I can't keep up with all the IDs of those tiles in a way that's intuitive) and I'm not sure if this is worth the effort to replicate.
