### ISSUE TITLE
[1.0.0.18][Accuracy Issue] In the original game, if you dig a ton in the same area, the nearest hole will snap to your position, re-dig, and give you nothing - In SMA it looks like you can create an infinite number of new holes and get items indefinitely

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#146]

**Comment by whitelilydragon** [comment]
This much, I did on purpose, because given the shorter nature of levels made for Shang Mu Architect, you don't want to spend too long farming for some decent health pickups before continuing on with a map.

Basically, I saw Milla's low success rate with digging as a pacing issue.
