### ISSUE TITLE
[1.0.0.18][Minor] Milla's falling animation doesn't play properly after she runs out of flying stamina

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#148]
https://user-images.githubusercontent.com/69790793/108475091-1a086600-7245-11eb-9682-bf6495480413.mp4

**Comment by whitelilydragon** [comment]
This is something I've known about, but forgot about amidst other bugs, omg-

It was a surprisingly easy oversight bug; all I needed to do was have the conditions for triggering the flutter check the stamina bar first- for some reason, it wasn't already doing that, so Milla's animations would get stuck in a loop until she landed o ^ o

Thank you for reporting!
