### ISSUE TITLE
[1.0.0.18][Major][DIFFICULT TO RECREATE] Being out of focus(?) before quitting a level can cause the background to get stuck indefinitely

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#149]
I've only had this happen twice, and I was out of focus for most of the game both times. Both times I had been playing multiple levels since I ran the game, but not completing any of them.
![image](https://user-images.githubusercontent.com/69790793/108475592-c34f5c00-7245-11eb-842e-0a4616eb829c.png)

**Comment by whitelilydragon** [comment]
What I'm curious of how you can play the game out of focus for long enough to trigger this? The game doesn't accept inputs for as long as the window is out of focus o ^ o

**Comment by benjistring** [comment]
I'm actually not sure if it's being out of focus that causes it. I've gotten this two more times on the newest build through regular gameplay. I'm not really sure anymore...

I got one after saving a level and trying to play it in the menu, and I got another in the editor itself where the display froze but the GUI didn't so I was able to save it and leave.

![BackgroundBug3](https://user-images.githubusercontent.com/69790793/108591930-0f6ecf00-7320-11eb-9c87-8d5580f8f4f7.PNG)

**Comment by whitelilydragon** [comment]
I think we've defeated this bug, among a few others, post-release. The game's general loop has been greatly tightened up, and an issue with loading stage file lists was also fixed. Please open a new ticket if this issue still persists!

Thank you for reporting!
