### ISSUE TITLE
[Release 1.0][Feature Suggestion] -Editor Only- Allow Milla's cube to regenerate sooner if it's been falling for a very long time (ie: waiting on it to fall outside the map)

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#150]
It can get a little annoying having to wait! More of a nitpick than anything. In the most extreme situations for me (sloping myself upward and throwing a cube at the highest point + some of the lag of the object heavy levels), it can take up to 15-20 seconds for her to be able to regenerate a cube.

Usually it irks me when I'm working with things very high on the map, and I don't have ground yet, so I have to wait for the cube to fall underwater too! Maybe I'm just impatient, eheh

**Comment by whitelilydragon** [comment]
I've set the cube to explode if it's 768 pixels away from the player's X/Y coordinates! This will look funny at higher zoom levels, but in-game zoom levels aren't allowed to go beyond 50% in play mode anyway, so it'd only be obvious in editor mode that Milla's cubes can't touch the bottom of the room at the 0% zoom level!
