### ISSUE TITLE
[1.0.0.18][Minor] Carol should stop rolling into a wall after a second, even if down button is held

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#151]
She be rollin'

SMA:
https://user-images.githubusercontent.com/69790793/108490875-13cfb500-7258-11eb-9fda-89852b9466f2.mp4
FP1:
https://user-images.githubusercontent.com/69790793/108490900-1af6c300-7258-11eb-9782-6b3cc4e8a3e7.mp4

**Comment by benjistring** [comment]
Solving this would also fix this issue!
![image](https://user-images.githubusercontent.com/69790793/108500467-aa09d800-7264-11eb-9aea-ce951d48bc8d.png)

**Comment by whitelilydragon** [comment]
This was a genuine accuracy issue! And what's silly is that the code *was* trying to unroll Carol after bumping into a wall, but it was missing an animation reset, so the roll exit conditions weren't working correctly, so I fixed it!

Thank you for reporting!
