### ISSUE TITLE
[1.0.0.18][Minor] Carol stays rolling if she changes direction on the ground

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#152]
The roll is very slow here!
https://user-images.githubusercontent.com/69790793/108491639-0109b000-7259-11eb-8223-1044a6058c0b.mp4
FP1 solves this by forcing her into a running state:
https://user-images.githubusercontent.com/69790793/108491595-f64f1b00-7258-11eb-8a83-00cd6ac61bc4.mp4

**Comment by benjistring** [comment]
Doing this would actually solve the issue from here before!
![image](https://user-images.githubusercontent.com/69790793/108499855-cbb68f80-7263-11eb-8b6c-a14914f51cd7.png)

**Comment by whitelilydragon** [comment]
I was able to fix this by simply removing additional checks for inputs during this stage of the roll! Fewer conditional checks and more accuracy. ^ v ^

Thank you for reporting!
