### ISSUE TITLE
[1.0.0.18][Minor] Characters hit by rotating spike obstacles (and regular sideways spikes) while not facing them get hit into them

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#153]
https://user-images.githubusercontent.com/69790793/108492989-a709ea00-725a-11eb-8be0-a6ef3f369df7.mp4

**Comment by benjistring** [comment]
Quick addendum! Found out this bug also exists for regular spikes too

**Comment by whitelilydragon** [comment]
I have adjusted the left side of the hurtbox by shrinking it 4 pixels, and increasing the right side of the hurtbox to be 2 pixels longer, so it's consistent between both sides! It was genuinely reaching too far out on the left side, and not nearly enough on the right side.

Thank you for reporting!
