### ISSUE TITLE
[Known bug][Physics] Characters tend to decelerate as they reach the end of slope pieces

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#154]
I think it's good to have a ticket for this just as a reference! Not sure if you would like to fix it for the upcoming release.

This is the most noticeable as Carol, who is able to roll at very low speeds.

https://user-images.githubusercontent.com/69790793/108498842-4c748c00-7262-11eb-8f4b-bab3931852e9.mp4
https://user-images.githubusercontent.com/69790793/108498854-4ed6e600-7262-11eb-9b5f-e65a260821b6.mp4
https://user-images.githubusercontent.com/69790793/108498864-50a0a980-7262-11eb-9a61-6b4be1c63bff.mp4

**Comment by whitelilydragon** [comment]
This report not only prompted me to investigate and fix this particular problem, it helped me realize I was applying a certain fix too broadly to slope factor, and now, slope movement overall is greatly improved!

https://user-images.githubusercontent.com/23007238/108959408-5c191980-7642-11eb-8a0c-c0fdeac6af75.mov

Thank you for reporting!
