### ISSUE TITLE
[1.0.0.18][Minor bug(?)][Feature Suggestion] The settings under the pause menu make noise when you press up and down despite not doing anything

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#155]
I suggest maybe having the cursor go back to the main pause menu when you press up and down here!
![image](https://user-images.githubusercontent.com/69790793/108499460-2a2f3e00-7263-11eb-947a-69d45b24cc8c.png)

**Comment by whitelilydragon** [comment]
This is something I wished I had thought of while working on the extra menu, so I went ahead and implemented it! It was as easy as adding two extra conditional exits for the menu! ^ v ^

Thank you for reporting!
