### ISSUE TITLE
[1.0.0.18][Minor] Collision from under small sloped slabs doesn't function properly in cramped areas

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#156]
https://user-images.githubusercontent.com/69790793/108502177-3c12e000-7267-11eb-8c4e-a47e8685a0a4.mp4

**Comment by whitelilydragon** [comment]
My solution to this, was to have a ground and ceiling check nearer towards the end of the collision code block, which stops you from moving if you're running into a shallow corner or ceiling. And it's still possible to escape out of it in any map that I've tried thus far!

https://user-images.githubusercontent.com/23007238/109107606-0a36c900-7700-11eb-9684-a96a7540f8fa.mov

Thank you for reporting!
