### ISSUE TITLE
[1.0.0.18][Minor] The dragonboost recoils off of bombs

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#157]
SMA:
https://user-images.githubusercontent.com/69790793/108502752-23ef9080-7268-11eb-9ee8-baa1b82da3ea.mp4
FP:
https://user-images.githubusercontent.com/69790793/108502775-2d78f880-7268-11eb-80b1-28d6d5145e2d.mp4

Explosive storage used as a level example-

**Comment by whitelilydragon** [comment]
I have fixed this by having the item tile collision sensors cleared if Lilac is dragon boosting! (Specifically the item wall sensors!)

Thank you for reporting!
