### ISSUE TITLE
[1.0.0.18][Accuracy Issue] When Milla holds an object and falls underwater, she immediately starts her swimming animation regardless if any buttons are pressed

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#158]
Not a bug! But I think it would be a neat and fitting change.

FP1:
https://user-images.githubusercontent.com/69790793/108503816-d8d67d00-7269-11eb-99cb-ce07a18a8a47.mp4

**Comment by whitelilydragon** [comment]
While this would be a nice little touch, it's a little late in development to partially rework how the swimming code works just to accommodate this for Milla. ; ^ ; I'm afraid of breaking things and creating more bugs, sorry.
