### ISSUE TITLE
[1.0.0.18][Minor] Resetting controls to default does not actually apply controls

### ISSUE THREAD

**Issue by Leo40Git** [whitelilydragon/ShangMuArchitect#160]
https://user-images.githubusercontent.com/7997354/108515637-f9d0b980-72cd-11eb-9040-764d6fb601bf.mov

Seems like resetting controls to default sets key binding *displays* correctly, but doesn't actually set the key bindings themselves.

**Comment by whitelilydragon** [comment]
The problem was that I had my ASCII codes all mixed up! It was both setting the in-game action keys to my preferred defaults *and* saving it to the game's configuration file that way, despite displaying FP1's defaults on-screen. o ^ o I'm glad y'all caught this.

Thank you for reporting!
