### ISSUE TITLE
[1.0.0.18][Minor] Character select button does not work properly if you make the game cursor snap to the character needed to play a character specific level and then move to a different one in the menu

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#161]

**Comment by whitelilydragon** [comment]
This is something I had accounted for in the code, but upon further investigation, it looks like I had made a typo and referenced the wrong variable to update while forcefully changing characters! o ^ o It's been fixed now!

Thank you for reporting!
