### ISSUE TITLE
[1.0.0.18][Minor] Milla's flight negates collision with downwards facing springs until she runs out of stamina

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#162]
https://user-images.githubusercontent.com/69790793/108572563-6eecc080-72c7-11eb-918e-42ed00739550.mp4

**Comment by whitelilydragon** [comment]
My hotfix solution to this was to have the main item ceiling sensor lower itself by four pixels, so that it can't miss scanning for item tiles while Milla is fluttering!

Thank you for reporting!
