### ISSUE TITLE
[1.0.0.18][Minor] Ghetto Blasters keep facing you during their death animation

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#164]
Not sure if this is in the original game? But they're the only enemy in SMA that keep doing this, so it's a little weird inconsistency

**Comment by whitelilydragon** [comment]
This was an easy fix! I had greatly overlooked this issue; most enemies who do look towards the player, do this during one of their animation states, as they cycle through relevant phases of movement where they should look towards the player. The ghetto blaster was unique in that it needed to do this looking around during more than one phase of its animation, so its looking code was outside of the state switch statement; so, whoops. O ^ O

Thank you for reporting!
