### ISSUE TITLE
[1.0.0.20][Accuracy Issue][Minor] Boosting through bombs duplicates them

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#168]
https://user-images.githubusercontent.com/69790793/108590597-3c6bb380-7319-11eb-930c-c053e16f2597.mp4

**Comment by whitelilydragon** [comment]
This is not so much a general issue with Lilac as it is the bomb flower object itself; it has a difficult time checking against attaching multiple copies of itself to neighboring bomb tiles and sometimes doesn't do it consistently; it's not an easy problem to solve.
