### ISSUE TITLE
[1.0.0.20][Minor][Known Bug] Volume of White Levels/Level Select/Fortune Night and Aqua Tunnel remix music very low after returning from a level or starting one that uses said music

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#169]
I know we all know this, but I'm filing a ticket for it anyway so you can feel good about putting this to rest! Godspeed on the rest of the bugs, Lilly! We love you!

**Comment by whitelilydragon** [comment]
As it turns out, I had multiple loose functions commanding the music's volume to be lowered, so- whoops. o ^ o

I also cleaned up audio playback for background music overall; now, even muting is applied consistently across the game with a new script!

Thank you for reporting!
