### ISSUE TITLE
[1-17-6-7-4][Major] Side loop pieces lack the same wall walking properties as other blocks

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#17]
![Shang-Mu-Architect-1175-Private](https://user-images.githubusercontent.com/69790793/90976133-628dd380-e4ef-11ea-9bc3-bf4566aa0107.gif)

weeeeeeeeeeee

**Comment by whitelilydragon** [comment]
Fortunately, this was fixed by a simple modification of the angle data on these tiles! I had erroneously set them to be angle 0, instead of angle 90- whoopsies

Thank you for reporting! ^ v ^
