### ISSUE TITLE
[1.0.0.20][Minor] If characters break a shield flower and quit the level before they get the shield, then play another level, they retain getting that shield

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#170]
https://user-images.githubusercontent.com/69790793/108590948-09c2ba80-731b-11eb-9ddf-bb08a996fecb.mp4

**Comment by whitelilydragon** [comment]
Oh, whoops o ^ o. This was an easy fix, at least; just had to keep two variables reset upon entering the level select room.
