### ISSUE TITLE
[1.0.0.20][Minor] If you break a target near a floating platform, it may get stuck there as if it were an enemy - Deckard

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#172]
I see Deckard didn't upload this one, so I thought I could do it for him-

https://gyazo.com/6c4f014af62d83e10a7e36950970cee6

**Comment by whitelilydragon** [comment]
I think this had something to do with child inheritance, when it came to grabbing objects like enemies, so I've added another collision sensor for targets to completely avoid this issue!
