### ISSUE TITLE
[1.0.0.20] [Minor] Milla's HUD covers invincibility timer

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#173]
![image](https://user-images.githubusercontent.com/69790793/108593549-3a115580-7329-11eb-91e6-9979ce434b49.png)

**Comment by whitelilydragon** [comment]
A lot of Milla's HUD elements got rearranged during development, but I hadn't thought to check this! So it's been fixed:

![Screenshot 2021-2-21 3-29-19-56](https://user-images.githubusercontent.com/23007238/108619784-0bf94780-73f5-11eb-9b08-e41ff46a7ffe.png)
