### ISSUE TITLE
[Release 1.0] [Feature Suggestion] Finally add the one-up music I made for you guys! (And invincibility music too)

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#174]

**Comment by whitelilydragon** [comment]
I was able to get past my hesitance to modify some thingies about the music management to get your 1up remix implemented! ^ v ^ Only problem is I don't know if you provided a remix of the invincibility theme before, or if you happen to know one from another musician we can ask for permission to use? I'm hesitant to use any music directly lifted from FP1 itself
