### ISSUE TITLE
[1.0.0.20][Accuracy Issue][Minor] RE: "Direction movement speed becomes butchered after trying to push a wall/object/colliding into a wall" - applies unevenly to solid objects

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#177]
https://user-images.githubusercontent.com/69790793/108594832-18b46780-7331-11eb-9528-32611c8c6d9d.mp4

**Comment by whitelilydragon** [comment]
The item tiles have their own unique set of sensors, so I missed checking against those as well, whoops! o ^ o It's been fixed!
