### ISSUE TITLE
[1.0.0.20][Minor] @ _ and # do not show up properly and "`"' is marked as "_" ingame and if any string contains / \ | : * " < > or ? the level will not save despite the game saying so

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#179]
The font at the bottom also doesn't recognize any special characters aside from - and %
![image](https://user-images.githubusercontent.com/69790793/108595678-00931700-7336-11eb-9815-391e74d190d6.png)
 Maybe you should completely omit special characters?

**Comment by benjistring** [comment]
![image](https://user-images.githubusercontent.com/69790793/108596110-c591e300-7337-11eb-9b18-78dc08ef9850.png)
Make sure you stress this too!

**Comment by whitelilydragon** [comment]
My solution to this, was to check each keyboard key press during the map file name box in particular, and if an "illegal" character has been typed, that character is deleted from the keyboard's key string *and* the map file name's string, and the user is given a warning that nothing fun is allowed : ^ P

https://user-images.githubusercontent.com/23007238/108619480-27fbe980-73f3-11eb-9555-ccc38bfed18f.mov

Thank you for reporting!
