### ISSUE TITLE
[1-17-6-7-4][Minor/Improvement(?)] Top facing springs reset player angle, even if running up walls.

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#18]
![Shang-Mu-Architect-1175-Private](https://user-images.githubusercontent.com/69790793/90978149-51998e00-e500-11ea-99a7-d5495548c59f.gif)
I do believe this was in the original(?) but maybe as a suggestion I push the player without resetting their angle in these situations.

**Comment by whitelilydragon** [comment]
Yes! This was possible in the original, but the mixed collision movement system currently doesn't accommodate this sort of reversal of directions, so it's an item on the to-do list for future updates; I'll have to rewrite some code to accommodate this.

So, #wontfix for now, but #willfix for future updates after 1.0! I do appreciate how observant all of y'all on the testing team are.
