### ISSUE TITLE
[1.0.0.20] Spikes have hitboxes on their underside

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#182]
https://cdn.discordapp.com/attachments/739994967186997329/813070334177050684/2021-02-21_16-29-55.mp4

The underside of spikes on all but the left facing tile have the player get hit them. It is unclear whether this is intended or not as there's no way to compare any situation to this occuring in FP.

https://user-images.githubusercontent.com/69774625/108630157-b60fb880-7463-11eb-85db-3762fdc2d4f2.mp4

**Comment by whitelilydragon** [comment]
This was really easy to adjust, because the game checks the background asset ID of the tile itself, before confirming the hit- so each and every flat surface sensor was checking way more spike tiles than they should have been.

Now, you can't get hit by the backsides of *any* spikes!
