### ISSUE TITLE
[1.0.0.22] [UI-Issue] The timer-UI overlaps if you exceed 100 Minutes of playtime in a stage

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#188]
https://gyazo.com/54ce8d508d6e973b2763445c4ba87640
https://gyazo.com/956b6acbd2d1cc73aabfa7b383ab350a

As seen in the above Screenshots, if the timer rolls over 99:99:99 and goes to 100:xx:xx and up, the first digit of the seconds will be overlapped.

**Comment by whitelilydragon** [comment]
This is something I had known about four years ago, but completely forgot about. o ^ o Whoopsie!

I simply fixed it by having the counter reset the minute counter to 99, if it attempts to go over 99 minutes; at that point, accurate measurements of time doesn't matter, and I'd have to modify the code for every element of the timer to work around that issue.
