### ISSUE TITLE
[1-17-6-7-4][Critical] Ladders crash the game if used while running down a slope

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#19]
![Shang-Mu-Architect-1175-Private (1)](https://user-images.githubusercontent.com/69790793/90978281-85c17e80-e501-11ea-994b-23ac0389b3e8.gif)

**Comment by whitelilydragon** [comment]
I think I've done as much as I can to fix this issue. Not only does it work now, it's relatively robust even when ladder tiles are placed inside loop pieces.

If there are still lingering issues, or side effects of the fixes that I missed, you're free to make another post about it! Thank you for reporting this one, it would've been a nasty thing to let go unnoticed before 1.0's release.
