### ISSUE TITLE
[1.0.0.24] [Minor] Falling out of level after completing it makes death sound multiply and double screen transition

### ISSUE THREAD

**Issue by N00neIsHere** [whitelilydragon/ShangMuArchitect#190]
If the final target is over a pit and the character falls into the pit after hitting it, the death sound will be triggered seemingly every frame until the game transitions back to the level select. It also causes there to be a screen transition in the level select, presumably the death fade in.

https://user-images.githubusercontent.com/77096912/109194235-39ccec00-7767-11eb-84e3-f61b802eb9e5.mp4

**Comment by whitelilydragon** [comment]
I fixed this with a lot more sanity checking and thorough disabling of the death state in situations where it isn't needed, while I was working on fixing another bug!

Thank you for reporting!
