### ISSUE TITLE
[1.0.0.24] [Minor] Loading new file in Editor causes two music tracks to play

### ISSUE THREAD

**Issue by N00neIsHere** [whitelilydragon/ShangMuArchitect#192]
When working on a level, if you choose the new file option in the editor, it will play the song for the level you were working on and the music for the new level at the same time.

**Comment by whitelilydragon** [comment]
This was an easy fix, because I made an oversight while refactoring how music was played back, whoopsie! o ^ o

Thank you for reporting!
