### ISSUE TITLE
[1.0.0.24][Major] Mashing buttons during the "quitting"-Screen transition causes various issues

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#194]
https://cdn.discordapp.com/attachments/739994967186997329/814624012876775434/2021-02-25_23-22-13.mp4

This recording shows what happens when you mash buttons during the screen transition as the player is attempting to quit a stage.
The game will start to get stuck in a loop with the "Loading"-Screen as it immediately selects a stage (which is always the first one in the level select without fail). You can still pause the game while the screen is frozen and navigate through the pause menu. Quitting again causes this loop to continue, while restarting allows you to play the stage normally.

**Comment by whitelilydragon** [comment]
I'm still investigating this issue, and believe I have a working solution, but I still need further self-testing of it first.

But, this issue has been overtagged; a bug can't have two classifications at once. If it deserves escalation to Class B, then the Class C tag is redundant.

**Comment by Deckardsmegson** [comment]
https://github.com/whitelilydragon/ShangMuArchitect/issues/191

I've noticed that this had been reported earlier before. I've added the duplicate issue tag.
