### ISSUE TITLE
[1.0.0.24][Milla] Supershieldbursting into an upper corner with Springs kills the player

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#197]
https://user-images.githubusercontent.com/69774625/109230905-ec339c00-77c5-11eb-9a04-101487806928.mp4

If Milla Uses her Super shieldburst into the formation of springs and walls, she will slip inside and get crushed inside.
(Also contains an issue regarding SSB into a Loop)

**Comment by Deckardsmegson** [comment]
https://user-images.githubusercontent.com/69774625/109231701-5862cf80-77c7-11eb-9cf7-bbf3ed046780.mp4

While there isn't a similar setup in FP1, we can assume that you are only supposed to bounce off the springs instead of clipping through them and into the ceiling, causing a death.

**Comment by whitelilydragon** [comment]
After triggering this myself, oh- owie! o ^ o This is quite bad!

I think I've fixed it by having it check against the spring launching timer; this way, if the spring's timer or a ceiling collision is triggered, it'll instantly cut Milla's "rocketdog" speed to 0!

Thank you for reporting!
