### ISSUE TITLE
[1-17-6-7-4][Minor] Springs will disappear if edit button is clicked mid-animation

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#20]
![Shang-Mu-Architect-1175-Private (2)](https://user-images.githubusercontent.com/69790793/90989740-f9d74300-e550-11ea-936d-a9241dea8671.gif)
While I'm not completely 100% sure what causes this, I do believe it has something to do with the timing of the edit button press, since the same spring will always disappear in edit mode if tested once more.

**Comment by whitelilydragon** [comment]
There's a variable for controlling the visibility of the spring tile within the player object. (This is for the pseudo-transparency effect that the springs use, flickering the sprite on and off in rapid succession!) Visibility of the tile was not being re-enabled by the editor itself, upon disabling the player, so I just fixed that.

Thank you for reporting, I would have never caught this myself!
