### ISSUE TITLE
[1.0.0.25] Spikes will kill the player at above 1 full healthpetal if your last state had 0 or 1 healthpetals

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#200]
https://user-images.githubusercontent.com/69774625/109341397-a7157580-786a-11eb-9cc6-e658df15153b.mp4

https://user-images.githubusercontent.com/69774625/109341410-ad0b5680-786a-11eb-9611-b1078d394674.mp4

If you enter a new stage and run into spikes while your health is at 1 full petal (2 half petals) the player will die. The same can be triggered if you restart the stage.

**Comment by whitelilydragon** [comment]
This was a pretty simple oversight, fortunately; one of the variables for protecting the player's life, if you take heavy damage while low on health, was not getting reset per room o ^ o

Thank you for reporting!
