### ISSUE TITLE
[1.0.0.25] Spikes deal delayed damage after a shield has been broken

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#201]
https://user-images.githubusercontent.com/69774625/109342070-9c0f1500-786b-11eb-84f9-0bc099c718a8.mp4

If you are on your final tick of health on a shield and lose it from touching a spike, you will immediately receive damage as the shield fades away (can cause death).

**Comment by whitelilydragon** [comment]
This is the result of outdated hurt checks in both the rotating spikes, the spike balls, *and* the tileable spikes.

The worst part is that the hurt state was broken in editor mode, as well, so that's been fixed.

Thank you for reporting!
