### ISSUE TITLE
[1.0.0.26] Shock Puppet's behavior timings are very inaccurate

### ISSUE THREAD

**Issue by NitroSplint** [whitelilydragon/ShangMuArchitect#203]
The Shock Puppet's behavior can be modeled as a loop of two states in sequence:
1. Idle: starting from the first frame when its shock hitbox is gone, to the frame after which the hitbox reappears, both inclusive
2. Attacking: starting from the frame when the hitbox appears, to the frame after which it disappears, both inclusive

In Freedom Planet, the Idle state lasts **142** frames, and the Attacking state lasts **100** frames. The latter consists of 12 cycles of shock attacks, each of which lasts (2 + 2 + 2 + 2 =) 8 frames, followed by a half-shock that lasts (2 + 2 =) 4 frames.

In SMA, the Idle state lasts a paltry **76** frames, and the Attacking state lasts **135** frames. The latter currently consists of 13 cycles of shock attacks, each of which lasts (3 + 2 + 3 + 2 =) 10 frames, followed by a half-shock that lasts (3 + 2 =) 5 frames.

This discrepancy has made the enemy much more difficult to tackle in SMA.

**Comment by whitelilydragon** [comment]
I've adjusted this the best I can; can't make this exactly frame-accurate, given how its animations are timed in Shang Mu Architect, but really, the biggest problem with the shock puppet is that you couldn't attack it while it was in its attack state. (Nor could you do this with the metal pup!) So, I've fixed those issues; had some loose conditional checks causing those issues, whoopsie o ^ o

Thank you for reporting!
