### ISSUE TITLE
[1.0.0.26] [Platform 5] Collision inaccuracies at the top edges

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#204]
https://cdn.discordapp.com/attachments/739994967186997329/815369708408406026/2021-02-28_00-45-16.mp4

When standing on the top edge of Platform 5, you clip inside of it slightly and don't stand on it properly as it is decending.

**Comment by whitelilydragon** [comment]
There's no way to rectify this with the engine's current understanding of surfaces, I'm sorry; things like this will have to wait.
