### ISSUE TITLE
[1.0.0.xx][Editor] Wide area deletion of tiles

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#207]
Since the implementation of quickly placing a large amount of tiles in the editor mode, it would be really beneficial if people could delete a large amount of tiles in a similar fashion. To prevent players from possibly losing progress unintentionally, maybe add a UI-Element to toggle this function.

**Comment by whitelilydragon** [comment]
This could be as simple as changing the right-click to delete function into a button hold event, as well, with a drawn rectangular box, like with tiling terrain tiles!

It's been added to the list, thank you for reporting!
