### ISSUE TITLE
[1.0.0.27] Killing a Keycard dropping enemy in Editor's testmode, makes a keycard spawn and stay on the map.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#208]
Reproduction:
- Make a short level, where an enemy has a keycard
- Test this level few times.
- Notice how keycard spawns every time enemy is killed, but it leaves a functional keycard in level design. If somebody doesn't correct this and removes keycards manually - not only an enemy will grand a keycard. Multiple keycards will be lying around that enemy.

**Comment by whitelilydragon** [comment]
I had done this purposefully, but didn't realize it'd be more of a nuisance than a help. o ^ o So now, when you get a keycard from an enemy in play test mode, it just makes the relevant sound effect and adds a key to the player's inventory; no flashy animation or anything. (I plan to add a keycard counter unique to play test mode, when I can!)

I've updated all enemies accordingly for this effect, thank you for reporting!
