### ISSUE TITLE
[1.0.0.27] Mysterious yeet off a vertical wall after going through a loop

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#209]
When you dismount off a vertical wall while going downwards out of a loop trail, you get launched with great force in a really weird direction.

https://user-images.githubusercontent.com/38583427/109436449-3e73f780-7a28-11eb-842a-b227a6e9665d.mp4

**Comment by ThatEps** [comment]
Here's the map I tested this on.

[Yeet demo map.zip](https://github.com/whitelilydragon/ShangMuArchitect/files/6058189/Yeet.demo.map.zip)

**Comment by whitelilydragon** [comment]
Ah, this is a three year old problem I had forgotten about: With flat surface tiles, some of them don't launch you off in any direction at all, you're just released from the surface tile and zip off; this also applies to some of the loop pieces.

A fix is coming as soon as I can figure out how to finish up launching positions for these missing launch cases *bricked*

**Comment by whitelilydragon** [comment]
This was a tricky fix, but I figured out how to make it work without also breaking the ability to clip onto other flat surfaces while connected to slopes- I also had to fix how this worked for declipping from the bottoms of sloped surfaces too; the code smell is so real tonight *bricked*

Thank you for reporting!
