### ISSUE TITLE
[1-17-6-7-4][Improvement] Bottom facing springs, despite their necessity to be vertically placed, still only respond to floor/bottom player sensors. 

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#21]
This makes sideways movement between two springs especially difficult. Example:
![Shang-Mu-Architect-1175-Private (3)](https://user-images.githubusercontent.com/69790793/90990022-cdbcc180-e552-11ea-81da-dcc863e425f0.gif)

**Comment by whitelilydragon** [comment]
This was a simple fix! I just had to set it check for the ground before causing wall collisions with ceiling springs, and now it's behaving as you'd expect. Thanks for reporting!
