### ISSUE TITLE
[1.0.0.27] Crash when approaching diagonally at high speed at a loop with hangbars underneath

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#210]
https://user-images.githubusercontent.com/38583427/109436889-94e23580-7a2a-11eb-9d76-3b5a34851c59.mp4

Map used to recreate this:

[Crash demo map.zip](https://github.com/whitelilydragon/ShangMuArchitect/files/6058217/Crash.demo.map.zip)

Crash log:

![Crash log](https://user-images.githubusercontent.com/38583427/109436931-d96dd100-7a2a-11eb-8e3b-8b7973a32e61.png)

**Comment by whitelilydragon** [comment]
After all the work I did to tighten up the loop exit controller, I completely missed giving the basic loop the same treatment! o ^ o I'm glad you caught this!

Here's the fix I applied to the loop object to make this work!

https://user-images.githubusercontent.com/23007238/109471302-96b5f400-7a3e-11eb-9847-01c1018239c5.mov

Thank you for reporting!
