### ISSUE TITLE
[1.0.0.39] Visual glitch in the Editor after collecting a certain number of crystals

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#214]
After hitting "Play" in the Editor and collecting a certain number of crystals, they create a visual artifact on the left side of the screen. This persists even if you exit into the menu and go back into the Editor.

Does not happen in Play mode.

![crystal](https://user-images.githubusercontent.com/38583427/110210118-e8c0a480-7e98-11eb-9a08-336eb87bce10.jpg)

**Comment by whitelilydragon** [comment]
Oh, whoops. o ^ o While I did simplify the conditional checks for when the player's object can draw/do things, that remaining check on the brackets is much more aggressive.

Not all parts of the HUD's drawing code were part of that check, either, so while the logic for animating the gems was frozen in the step event, the code for drawing them on the GUI layer was not disabled. This has been fixed!

Thank you for catching that!
