### ISSUE TITLE
[1.0.0.39][Minor] "Inheriting"/ Destroying a Shieldflower while playing in Editormode permanently removes their placed Shield particles.

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#215]
https://cdn.discordapp.com/attachments/739994967186997329/817929649103437864/2021-03-07_02-17-22.mp4
If you destroy a shieldflower in editormode while they have their shield particles active, it will be permanently removed, as shown here. The player would have to manually reapply it again within editormode.

**Comment by whitelilydragon** [comment]
This was an easy fix, all I had to do was add a check against this before the object attempted to destroy itself.

And I relabeled it to Class C, because this is a genuine GUI issue insofar as "Oh no, now I have to replace all of these objects that I destroyed"

Thank you for reporting!
