### ISSUE TITLE
[1.0.0.42] At high falling speeds, wall sensors clip against item tiles before the floor sensor does

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#220]
https://cdn.discordapp.com/attachments/739994967186997329/818641455983362058/2021-03-09_01-26-23.mp4

As shown in this scenario, you might get zipped and stuck inside a wall if you fall onto a spring fast enough that is between a wall and another item tile.

**Comment by whitelilydragon** [comment]
This is a general problem with item tiles, not just the springs. This will be fixed as soon as I can refactor items to be their own dedicated objects, instead of tiles; I'll close this ticket once I've implemented the new system.

**Comment by whitelilydragon** [comment]
I am now closing this ticket because we've pushed a new update that fixes this issue, among many others!
