### ISSUE TITLE
[1.0.0.42][Carol] Rolling down on ceiling loops causes her to reverse course if the connected tiles are ceilings

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#222]
https://cdn.discordapp.com/attachments/739994967186997329/818647958743416862/2021-03-09_01-52-13.mp4

If you're rolling down a loop / slope as Carol, you may get sent backwards, if the following tiles are Flat ceilings. You may also clip inside them, causing a crushing condition

**Comment by whitelilydragon** [comment]
I see this more as a genuine functionality issue more than an accuracy-related one, as with previous reports of collision issues! I'll close this ticket once I have a solution for this problem!

**Comment by whitelilydragon** [comment]
Long story short, I spent hours figuring out that this was a systematic problem with general character movement, not just Carol. So, now there's extra code to deal with this scenario in the sections for handling flat ceiling running. It's not quite as elegant as I'd like yet, but it should be so much nicer than the characters getting stuck in loops like before:

https://user-images.githubusercontent.com/23007238/113466886-36371f80-940d-11eb-867f-c8a19a9980b0.mov

How it behaves now:

https://user-images.githubusercontent.com/23007238/113466892-44853b80-940d-11eb-9067-bbe1736ee102.mov

https://user-images.githubusercontent.com/23007238/113466897-4ea73a00-940d-11eb-8110-f5c53f985b05.mov

Thank you for reporting!
