### ISSUE TITLE
[1.0.0.42] [Major] Spawning a loop within small ramps crashes to desktop.

### ISSUE THREAD

**Issue by frogmoss10** [whitelilydragon/ShangMuArchitect#223]
I put a loop spawn object inside a loop made of small ramp tiles and the game threw the following:
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Destroy Event
for object obj_loop_logic:

Variable obj_loop_logic.enemy_shifting_tile_left(101877, -2147483648) not set before reading it.
at gml_Object_obj_loop_logic_Destroy_0
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_obj_loop_logic_Destroy_0 (line -1)
called from - gml_Object_obj_loop_logic_Create_0 (line -1) - <unknown source line>
called from - gml_Object_obj_level_editor_Step_0 (line -1) - <unknown source line>

**Comment by whitelilydragon** [comment]
While I did fix this crash, I've more simply addressed this by getting rid of the enemy reverse direction tiles that the loop controller places; those might have proved more of an annoyance to players than a help, in the long run.

Thank you for reporting!
