### ISSUE TITLE
[1.0.0.44] - Aqua Surface plays after selecting a gameplay option from the Main Menu; the song flickers on and off during loading sequences

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#227]

**Comment by whitelilydragon** [comment]
This was a hack I implemented to get around a problem with the editor not wanting to play music at the start of the room, but I had broadly applied it to any room that the title screen object could lead the player into, so I've fixed that!

Thank you for reporting!
