### ISSUE TITLE
[1.0.0.44][Difficult to reproduce] Selecting key card terminal produced a game breaking error

### ISSUE THREAD

**Issue by Kodipher** [whitelilydragon/ShangMuArchitect#228]
### Selecting key card terminal threw an error:
![image](https://user-images.githubusercontent.com/45706822/110790393-09667100-8282-11eb-9d78-a0e037b26226.png)
If you ignore, the item preview sprite disappears and the error is thrown again, every frame, preventing any further play.

The first time it happened out of nowhere.
I could not find a consistent way to recreate this, but I managed to get the error multiple times through combinations of:

- selecting random springs and "?" options
- selecting random items and mods excluding the spawn points, key card, key card door and terminal
- placing springs
- trying to place the terminal itself while no doors are
- trying to erase object with the terminal selected
- waiting in the menu

before selecting the terminal.

Sometimes the error is throw, other times not.

**Comment by whitelilydragon** [comment]
I've tightened up how the item preview is allowed to draw! Please let me know if this persists in the current build!

**Comment by whitelilydragon** [comment]
I am closing this ticket for a lack of responses, but if this issue still persists, it would be triggered differently and result in a different error code, too, most likely.

Please open a new ticket if this issue still persists in updated builds of the game!
