### ISSUE TITLE
[1.0.1.0][Slope Collision] Walking on a wall into a basic slope clips you through them

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#229]
https://cdn.discordapp.com/attachments/739994967186997329/819627853942620188/2021-03-11_18-46-54.mp4

As seen here, if the player walks at a straight angle towards a slope tile, you clip through it.

**Comment by whitelilydragon** [comment]
There are still many funny edge cases, but I have at least provided ways for flat surface running sensors to detect slope ceiling surface types, so now the characters' declip from sloped ramps when they touch them!

Thank you for reporting!
