### ISSUE TITLE
Carol- Wild Kick Cancel while double jumping on bike

### ISSUE THREAD

**Issue by NGeoD** [whitelilydragon/ShangMuArchitect#230]
When cancelling bike's double jump with Wild Kick, the duration of the Wild Kick only lasts as long as the remaining duration of the initial double jump before cancelling into a fall animation.

https://user-images.githubusercontent.com/48820145/110866800-50a52f80-828b-11eb-9f04-9c5efe0b5500.mp4

**Comment by whitelilydragon** [comment]
This was a surprisingly simple oversight on my part! ; ^ ; Carol's bike's double jump state wasn't getting cleared upon performing her wild kick attack, so just tweaking that fixed this issue!

Thank you for reporting!
