### ISSUE TITLE
[1.0.1.51] Enemies that are stacked on top of each other only die one at a time

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#233]
https://cdn.discordapp.com/attachments/739994967186997329/824066469850513468/2021-03-24_00-44-08.mp4

You can stack multiple enemies on top of one another and they form an enemy unit which only gets hit in segments.

**Comment by whitelilydragon** [comment]
This is a behavior you may be familiar with in Freedom Planet 1, as well. FP1 can't scan for multiple scenery objects and enemies within the same frame. Shang Mu Architect's attack system behaves exactly the same, for better or worse.

I can't begin to imagine how to fix this without introducing show-stopping frame lag each time a character attacks, sorry.
