### ISSUE TITLE
[1.0.1.53][Collision] The underside of Loops can be zipped through (May cause crushing)

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#235]
https://cdn.discordapp.com/attachments/468385806340587532/824619483082522694/2021-03-25_13-20-15.mp4
https://cdn.discordapp.com/attachments/468385806340587532/824619507037110272/2021-03-25_13-18-03.mp4

In this instance, the collision from the underside of loop tiles is broken and causes zipping (into blocks which causes crushing). This issue has occured before but came back.

**Comment by whitelilydragon** [comment]
This was a simple fix. I had simply forgotten to make the loop exit object spawn flat surface tiles on the undersides of slope tiles that it had disabled the 2D logic objects from- whoopsie o ^ o

Thank you for reporting!
