### ISSUE TITLE
[1.0.1.55][Items] Milla can pick up a broken 1Up cage after it was attacked

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#236]
https://user-images.githubusercontent.com/69774625/112738391-f383cc00-8f62-11eb-8c27-f60228508e9b.mp4

The video shows that if you try to summon a cube or otherwise would want to pick up the 1Up Cage item by holding the attack button as Milla, even after it's already broken open, she can pick it up and throw it aroudn

**Comment by whitelilydragon** [comment]
I was able to fix this by changing the sprite_index of the 1up chibi object, as it transitions into its state where it's freed of the cage.

Basically, the chibi draws its sprite based on a variable separate from the object's sprite index- an index Milla's pickup code is checking against for picking up/deleting various objects. It is okay for Milla to respond to the internal sprite index where the chibi is stuck in the cage, but with the sprite index not changing to reflect the change of state- she's able to pick it up at any phase of its movement if it's within range of the object scanner!

So, this was a simple fix, thank you for reporting!
