### ISSUE TITLE
[1.0.1.55][Items] Targets and other items get destroyed by enemies from way further away

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#237]
https://user-images.githubusercontent.com/69774625/112738507-c8e64300-8f63-11eb-93e9-d7e5cb46b913.mp4

The video shows how while there's enemies both on screen and offscreen that they destroy targets or gem-boxes from way further away than they should.

**Comment by whitelilydragon** [comment]
This to my knowledge doesn't apply to enemies _in general_, so much as a horrendous typo in the temp variables that defined the firespitter's hitbox

Not setting the hitbox's Y parameters relative to the Y position of the firespitter meant that its hitbox was as tall as the ceiling of the room, no matter how far it's fallen! That's been fixed- and may have been a problem with the firespitter for this entire time; we just never caught it before.

Thank you for reporting!
