### ISSUE TITLE
[1.0.1.55][Items][Collisions] Walking into diagonal Springs on a ceiling makes you phase through them

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#238]
https://user-images.githubusercontent.com/69774625/112738596-7a857400-8f64-11eb-8c08-6b0a777d3712.mp4

While walking upsidedown on a ceiling into diagonal springs, you phase through them. Should you hit a wall, you also clip inside of it

**Comment by whitelilydragon** [comment]
This was a pretty simple fix! For some reason, the spring object's script wasn't clearing the player's current angle or transitionary angle, which couldn't allow the player to "let go" of the ceiling, even if the spring held onto the player's X/Y coordinates! The scanner boxes for the ceiling springs also weren't high enough for it to be read by the player's X/Y coordinates, so I raised them up; it's working now!

Thank you for reporting!
