### ISSUE TITLE
[1.0.1.57][Function UI Page 2] Reset message gets stuck on the screen if you don't finish restarting

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#239]
https://user-images.githubusercontent.com/69774625/113526063-bc439980-95b8-11eb-9c15-4ebc593c5b92.mp4

If you press the "confirm" button on the F2 function in the UI, the text "Resetting..." gets stuck on the GUI and won't go away, unless you finish resetting by holding it for much longer.

**Comment by whitelilydragon** [comment]
Closing this ticket because it was fixed in current builds!
