### ISSUE TITLE
[1.17.6.7.14][Normal] Springs still can bounce you in the wrong direction in certain configurations.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#24]
![Bounce](https://user-images.githubusercontent.com/7067769/91483484-14d6e980-e8a8-11ea-859d-119bfc642790.gif)

On this GIF, you can see that 2nd time, character seemingly touched two bouncepads at the same time, which caused the bounce in the different direction. This is continuation of https://github.com/whitelilydragon/ShangMuArchitect/issues/3 it seems

**Comment by whitelilydragon** [comment]
I just fixed the problem! Turns out I had a typo in one of the spring interaction scripts. (The right item tile sensor was configured to launch you at 45 degrees on left-diagonal springs, rather than 135 degrees!) I'm glad you caught this!
