### ISSUE TITLE
[1.0.1.64] Crystal counter glitches out sometimes

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#242]
From Flad's stream:

https://user-images.githubusercontent.com/38583427/118185487-40edc700-b445-11eb-8f74-0ca2a1cb7ffe.mp4

**Comment by whitelilydragon** [comment]
I caught this one some time ago, and was able to fix it in the current rolling release build!

Apparently, some hard-coded text-drawing positions hadn't been updated after I updated the game's HUD, so- yeah, we had a problem.

Thank you for reporting!
