### ISSUE TITLE
Bug Report: Falling through part of a map and becoming trap in it.

### ISSUE THREAD

**Issue by h4r1337qu1nn** [whitelilydragon/ShangMuArchitect#246]
Hi hi! Just submitting a bug report for a glitch that I had recorded on video.

It seems that there are instances where I fall through a part of the map that is diagonal from the floor to the wall and I am unable to escape. I was left with no option but to restart the level. Hoping to see this bug get fixed as I really enjoyed playing the game and I wouldn't want anyone else to face the same glitch that I did and have a not so good experience. The video clip will best describe the bug.

https://user-images.githubusercontent.com/21151785/121257129-5656e500-c87b-11eb-8e7e-85f9b4dfa00b.mp4

**Comment by whitelilydragon** [comment]
Sorry for taking so long to reply!

While the game still has longstanding issues to sort out with collisions in more specific scenarios, this is no longer one of them, as of some refactors to the springs' behavior, post-SAGE: I can no longer force Lilac or even Spade underneath the springs

https://user-images.githubusercontent.com/23007238/164101708-894777fe-5b57-4a53-b643-eab3b7eb4e69.mov

Thank you for reporting!
