### ISSUE TITLE
[1-0-1-93][Minor] Milla's controls on HUD don't update with rebinding on a controller

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#247]
Reproduction:
1. Use gamepad.
2. Go to options and rebind Switch from RB to B.
3. Play as Milla.

Current effect:
1. RB is still on the game's HUD

Expected result:
1. B is shown except RB

**Comment by whitelilydragon** [comment]
This is a good find! The scripts that control how the HUD's versions of the gamepad's buttons weren't updating the Switch button's bindings at all between rooms/maps, so this could've posed serious problems in general, not just for Milla! Especially if we find a use for the Switch button for Lilac and Carol, and those bindings need to be reflected in the in-game movelist

This has been fixed. Thank you for reporting!
