### ISSUE TITLE
[1-0-1-93][Normal] Destroying MegaCrate in editor mode will remove it from the stage.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#248]
1. Pop a MegaCrate in level creator
2. Enter play mode
3. Destroy crate
4. Exiting the play mode will not return the MegaCrate in place.

**Comment by whitelilydragon** [comment]
This was an oversight while actively developing the mega items, so I went ahead and fixed it! Thanks for reporting!
