### ISSUE TITLE
[1.17.6.7.14][Major][Hard to reproduce] Crashes/Screenlocks on restarting the previously completed level

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#25]
**EDIT:** After few instances of straight reproduction. I cannot reproduce it again. I will update this task when I will have more data.

Sample level causing issues is provided.

After beating the level and entering it again. Two things can happen:

1) Game crashes on screen LOADING...
2) Screen LOADING... never fades, but game is playable and responsive "underneath"

![image](https://user-images.githubusercontent.com/7067769/91484002-ce35bf00-e8a8-11ea-9829-fd0331acf3eb.png)
[Bounce Backup 1.zip](https://github.com/whitelilydragon/ShangMuArchitect/files/5138268/Bounce.Backup.1.zip)

**Comment by whitelilydragon** [comment]
I believe this might be a rare occurrence where the transition can get "stuck", so I've placed more safety measures to completely clear the transition, should it not have already cleared itself after 30 frames of the room's start. If a more specific way to reproduce this bug still occurs, I'd appreciate a new ticket with the relevant symptoms.
