### ISSUE TITLE
[1-0-1-93][Minor] Collisions on Orange cube can be wonky at times.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#250]
Best to reproduce it on the start of Explosive Storage. Throwing the Orange cube in the hole can result it landing "in-between" tiles, like on this image.

![Screen1](https://user-images.githubusercontent.com/7067769/129251091-e9c8ca46-965c-43eb-a150-7dbde7f72a9f.png)

**Comment by whitelilydragon** [comment]
This is something I would need footage for, to see how it triggers. I have difficulties triggering this myself.

**Comment by NBlastMax** [comment]
Got it. I will send you a video after work

**Comment by NBlastMax** [comment]
Dang it. I spend a lot of time to reproduce it and it only happened once this time out of 5 minutes of straight throwing those blocks. I think you can chalk it off as super-rare, maybe reopen when more reports of consistent places will emerge.

**Comment by whitelilydragon** [comment]
I will close the issue for now, but yes, this looks like an extreme edge case, and that could be subject to change as I rework parts of the engine. We'll see if it crops up again.

In the meantime, thank you for reporting!
