### ISSUE TITLE
[1.0.1.72] Mega-box objects have weird collision when falling on them from the top.

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#253]
https://user-images.githubusercontent.com/38583427/129786699-1fd57c27-880d-4c37-a31e-51680618f95f.mp4

**Comment by whitelilydragon** [comment]
I was able to fix this purely with a point_distance check for the player's X/Y coordinates! If the player's X/Y coordinates are within 24 pixels of the box's center point, it stops granting permission for the player to grab/push it!

I have also tweaked the method for how it's checking for the player's position against its sides, which should, at the very least, be more accurate

Thank you for reporting!
