### ISSUE TITLE
[1.0.1.72] Map description text hops to a new line back and forth at certain text lenghts.

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#254]
This is probably due to the text cursor being a character itself.

![Text hop](https://user-images.githubusercontent.com/38583427/129787169-10e56fe0-86fc-4d65-9973-79d5a23e8282.gif)

**Comment by whitelilydragon** [comment]
Thanks to our friend Leo, ( https://github.com/Leo40Git ) this issue has been fixed! ^ v ^ Each time a character is type, its length is compared with the desired width, and splits up the text as appropriately as it can. (Text can still escape the box in certain edge-cases, but it's no longer jumping around the box's margins, either!)

https://user-images.githubusercontent.com/23007238/206873191-93890a2d-9fab-4700-a5d1-96eaa9a9ba2b.mov

Thank you for reporting!
