### ISSUE TITLE
[1.0.1.72] Layer changers have the text of layer setters in their sprites, and vice versa.

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#255]
When you select a Layer Change object in the menu, the text will say it is a layer changer (either high or low) but its sprite will say it's a layer _setter_. This is also the case for the Layer Set objects - their sprites say "Layer Change", leading to utter confusion.

![layer changer](https://user-images.githubusercontent.com/38583427/129788223-da62524e-ec0b-4b93-8e08-282227a577c8.jpg)

![layer setter](https://user-images.githubusercontent.com/38583427/129788467-f192358d-06ff-4ef6-a8f2-5977931d117b.jpg)

**Comment by whitelilydragon** [comment]
Oh wow, this affected even the Quick Tools submenu, so I've swapped out the appropriate descriptions. I'm glad you caught this!
