### ISSUE TITLE
Lilac's Alt Skin changes to FP1 Skin while on Play Mode.

### ISSUE THREAD

**Issue by Zurtur** [whitelilydragon/ShangMuArchitect#258]
Just downloaded the SAGE Version and wanted to see the new changes to Milla by changing from 
Lilac to Milla on a stage that I had in progress. (Since I haven't played in a while.)
When I change back to Lilac in Play Mode from the Editor, she was on her FP1 outfit instead of the Alt Skin.
I checked real quick the "gamedata" file in confusion just to see if I had the Alt Skin option set to "1" but, nope.
It's on "0" as of right now. (As shown in the Image.)
Then I tried to do the same with the value set to "1" this time just to see if it reverted from OG to Alt but, no dice.
(Seems to only do so when I'm using the Alt Skin.)
I also tried to see if the effect maintained if I closed and re-opened the "Editor" and it did. 
Then I went to "Play" from the Title Screen to see if the effect carried over there as well and it did... until I scrolled 1 option down and changed back to Alt!
However, even if it has an In-gamne solution, it is still something not meant to happen so...
I hope it has a fix for future versions. 
![image](https://user-images.githubusercontent.com/51940596/130337845-67cd9920-ce68-4da8-bbcf-8bd788ec1c8d.png)

**Comment by whitelilydragon** [comment]
This is less a bug and more a lack of design clarity on my part.

In short, pressing the 1 key changes between Lilac's FP1 skin, and SMA skin. This means you'll need to press 1 twice to see her SMA skin, when flipping between characters in editor mode.

What I think I could do, is make the FP1 skin switch a key/button hold event, (where you hold the key for 30 frames) rather than a press-once toggle to change skins. Would that make more sense?

**Comment by Zurtur** [comment]
(You're fast on replies, I must tell!)
Now that you explained, I was thinking to keep it as it is, but, when the Alt skin is on Default, as well as when you switch back to Lilac, just keep her on the Alt Skin and make it so the option to alternate in between FP1 and SMA outfit is much intuitive.  
Like, a notch on the left side of the button icon for Lilac that briefly pops in and out saying "FP" or "SMA" depending on which one is being used.
Feel like that could work.
(Or at least that's the idea I have for a solution.)

**Comment by whitelilydragon** [comment]
My solution for now was to fix the 1 key to *always* start off on Lilac's SMA skin, then additional key presses flip between her FP1 and SMA skins!

In the future, I may add another player slot that makes her FP1 skin less of a secret. For now, at least it should be more clear what's going on.

Thank you for reporting!
