### ISSUE TITLE
[1.17.6.7.14][Normal] "Ghost" sounds of enemies

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#26]
[Bounce Backup 1.zip](https://github.com/whitelilydragon/ShangMuArchitect/files/5138271/Bounce.Backup.1.zip)

In the provided level, you can sometimes hear enemies when they are not near. This might be connected to the recent fixes on the audio. At the start of the level, you cannot hear enemies, which is correct. After going through the level a bit and eliminating all enemies you can still hear some being nearby when they aren't.

Maybe enemy objects are not removed properly and they still generate sound after smashing them up?

Needs more investigation.

**Comment by whitelilydragon** [comment]
The enemies are being deactivated properly, it's just that the inactivation region is fairly large for objects, so in densely packed stages, you can still hear enemies that are a floor or two above you.

I've corrected this by tightening up the distance at which their sounds can travel before they're supposed to stop. You've shown with your stage that Turretus and Firespitter are indeed enemies who also need to be silenced beyond the camera's boundaries, for their constant recurring noises. Thank you for reporting!
