### ISSUE TITLE
[Suggestion] More level themes varied in scope and style (possibly with matching tiles if possible)

### ISSUE THREAD

**Issue by TidesSonic** [whitelilydragon/ShangMuArchitect#260]
I'd be completely hyped up for an airship or final dreadnought-inspired level background to make something extremely awesome!

**Comment by whitelilydragon** [comment]
As you may have seen in recent updates to our rolling builds, we're now up to three complete tile sets, over ten backgrounds, and a new fourth tile set is coming in chunks at a time! We even have a space background now.

I hope to have at least five healthy sized tile sets, with half of a sixth tile set planned for a particular stage, for the finished game. But as Shang Mu Architect is now, it's quite a bit more content compared to its last SAGE build, and more is coming!
