### ISSUE TITLE
[1.0.2.7] Placing a pedestrian signal on the map and saving it then causes a fatal error and map deletion

### ISSUE THREAD

**Issue by 23LIEF** [whitelilydragon/ShangMuArchitect#262]
The new object added in the rolling build [1.0.2.6] causes a serious problem, placing the pedestrian signal on the map, then saving, causes the game to suffer a fatal error by closing it and deleting the .map file(the level).
 
 https://user-images.githubusercontent.com/89137194/133183020-d9144ce4-3a20-4bd4-9fc1-7e3a0e36e54a.mp4

**Comment by whitelilydragon** [comment]
Oh! This is such a simple oversight, it pains me that you lost a map to this ; ^ ;

I've fixed it for the upcoming build, at least; the crosswalk just needed some variables initialized
