### ISSUE TITLE
Some slopes not detecting Spade's card properly?

### ISSUE THREAD

**Issue by Zurtur** [whitelilydragon/ShangMuArchitect#264]
https://user-images.githubusercontent.com/51940596/151712786-ffb9ba96-e3d7-4f06-adba-790ab4f025af.mp4

Pretty odd, if you ask me.

**Comment by whitelilydragon** [comment]
I'm stumped on this one, as well! Spade's cards are now using the same slope check array that enemies do, for more consistent card collisions regardless of Side A or Side B collision maps being active, and he's still doing this.

Hopefully, I'll figure it out eventually, but for now, I'm leaving the ticket open until I figure out what's wrong.

**Comment by whitelilydragon** [comment]
I was able to fix this thanks to noticing some excess code in Spade's cards. They were performing ignore flag checks that only the player should've been doing, which ended up making Spade's cards ignore almost all left-facing loop pieces!

Thank you for reporting!
