### ISSUE TITLE
[1.0.7.4] [Minor] Characters will sit on benches at an angle if they are on a slope before sitting down

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#265]
![image](https://user-images.githubusercontent.com/69790793/163077131-2ca6975f-0439-44bb-b106-76f890128d3c.png)

**Comment by whitelilydragon** [comment]
Oh! This is an interesting oversight- I was able to fix it by just having the bench parent object double-check that the player's current angle is 0, before "grabbing" them!

Maybe at some point, I could have benches rotate against slopes, so people can get *extra* silly with these things, but for now- this has been disabled. Thanks for catching this!
