### ISSUE TITLE
[1.0.7.4] [Minor] Bomb and Mega Blocks can be pushed into walls

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#268]
https://user-images.githubusercontent.com/69790793/163079016-08bf6e3b-4a74-44e4-a38b-9c6178abb7ac.mp4

**Comment by whitelilydragon** [comment]
I was able to fix this optimally, by having two proper wall collision scanners on both sides during the 16-frame timer that activates whenever it's touching a wall! That fixed the issue for all mega items and blocks!

Thank you for reporting!
