### ISSUE TITLE
[1.0.7.4] [Minor] Yellow Pot is marked as Green Pot in the items menu

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#269]
![image](https://user-images.githubusercontent.com/69790793/163079859-c55e0b19-88f4-4648-9c84-e05dea6acb73.png)

**Comment by whitelilydragon** [comment]
I think I saw this months ago, and didn't make a note of it for my to-do list, so I'm glad you caught this- because I keep forgetting > ^ <
