### ISSUE TITLE
[1.17.6.7.13][Normal] Spiky balls get displaced on reloads.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#27]
![image](https://user-images.githubusercontent.com/7067769/91643317-4ed3f700-ea32-11ea-92fd-fde76e6b77e8.png)

Those spiky balls cannot seem to stay in one place. They go up and left every reload of the map.

**Comment by whitelilydragon** [comment]
I believe have fixed this issue! If it persists, please open another ticket.
