### ISSUE TITLE
[1.0.7.4] [Typo] "gem" should be "gems" in the Mega Yellow Pot description

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#270]
![image](https://user-images.githubusercontent.com/69790793/163080016-276736d8-7360-41cf-9b2e-4cdcacf2db7f.png)

**Comment by whitelilydragon** [comment]
Oh, the things I miss when working on things at 5AM. > ^ < I'm glad you pointed it out, I just had to change one string in the editor's object.
