### ISSUE TITLE
[1.0.7.4] [Minor] Page labels at the bottom of the editor menus are inconsistently named

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#273]
Some are marked "Page 1 of 2" while others are marked "_____ Section - Page 1 of 2"

![image](https://user-images.githubusercontent.com/69790793/163083718-3a2eb461-1f6e-4856-a784-1baa11866236.png)
![image](https://user-images.githubusercontent.com/69790793/163083748-bd7594a2-14c7-42d8-a0a9-501d1b107e88.png)

**Comment by whitelilydragon** [comment]
As you might have seen with the Enemies/Bosses section labels, I think I had plans to put more than just one type of actors in this section, but if I were to do that at this point, I would simply make mod chips that modify how existing actors behave, not arbitrarily define which types of actors are allowed to behave in certain ways.

So, now that you got me thinking about it, I've removed this extra text from the editor!
