### ISSUE TITLE
[1.0.2.3] Deleting non-top left part of loop controller causes error "Cannot delete special object flag tiles" on further deletes there

### ISSUE THREAD

**Issue by hsandt** [whitelilydragon/ShangMuArchitect#276]
Reproduction steps:
1. Add a loop controller from Items and Gimmicks ("Simple Mode" in the Manual)
2. Select any tile from Tiles (to enable tile deletion again) and delete any quarter of the loop except the top-left quarter (which deletes the whole loop properly) => only the quarter is removed.
3. Keep holding the delete button (right-mouse button or E) hovering the surroundings => an error message "Cannot delete special object flag tiles" with error SFX is spammed.

![Deleting non-top left part of loop controller causes Cannot delete special object flag tiles](https://user-images.githubusercontent.com/1067772/173236670-22e7685a-0933-48bf-a212-e4e7a95d897a.png)

4. Delete the top-left part. This time, all "flag tiles" have been cleaned, and the error stops spamming.

Note: I initially got a different bug, a crash that I couldn't reproduce. After adding a bunch of tiles, a loop controller on top, then deleting tiles on the loop and around, I got:

> ############################################################################################
ERROR in
action number 1
of  Step Event0
for object obj_loop_logic:

> Tile does not exist.
at gml_Object_obj_loop_logic_Step_0
############################################################################################

> stack frame is
gml_Object_obj_loop_logic_Step_0 (line -1)

But since I couldn't reproduce it even once, I could not define precise repro steps so I didn't open a ticket about that. However, I could at least spot the "flag tiles" error instead, so posting this one instead.

**Comment by whitelilydragon** [comment]
While I do appreciate that you were able to reproduce the problem, I encourage you to update the version you're playing! 1.0.2.3 is nearly a year out of date; it's missing everything from the inclusion of Spade, Carrie, another alt skin for Milla, mouse support for player mode, better analog stick support, more tile sets and backgrounds, more gimmicks, and other quality of life features for the editor itself-

And just today, I decided to move one of the rolling builds to the "stable" downloads channel. The instances of confusion over which version to download are becoming too many, and I believe the latest rolling build has enough bug fixes and QoL to be a worthy update.

That said, the crashing issue should have been addressed in the latest updates! But I found an efficient way for the loop controller to check whether or not all of its tiles exist, and it will now delete itself if one or more pieces go missing. You will see that fix in version 1.0.8.8 in the releases section of this GitHub page!

https://github.com/whitelilydragon/ShangMuArchitect/releases/tag/v1.0.8.8

Thank you for reporting!
