### ISSUE TITLE
Milla's Barrier Shield does not reflect/block enemy projectiles

### ISSUE THREAD

**Issue by ChaosController** [whitelilydragon/ShangMuArchitect#279]
In the original game, Milla's Barrier Shield could be used to reflect almost every projectile in the game, and the ones that couldn't be reflected could most likely be blocked:

https://user-images.githubusercontent.com/110129024/181646288-aae12047-9942-42e7-baf3-fdf200ddfb64.mp4

https://user-images.githubusercontent.com/110129024/181646299-64ffbb1a-122e-4756-afd9-48abb94d6ee4.mp4

https://user-images.githubusercontent.com/110129024/181646304-ef8c8a93-108a-4442-9a17-835a381f7cb2.mp4

This behaviour, however, is almost entirely missing in SMA:

https://user-images.githubusercontent.com/110129024/181646412-206b2406-e4e4-4d0c-9769-7ce38583677d.mp4

https://user-images.githubusercontent.com/110129024/181646443-c7f0c53b-9ebd-4616-8ec0-9da60610e2af.mp4

https://user-images.githubusercontent.com/110129024/181646455-f80feb77-2b44-44e0-bc92-4f3eff703b1b.mp4

The sole exception to this is the DNA Cannon and its moving variant, the RNA Cannon, which can still be blocked. But rather than blocking the projectile like in the original, the projectile instead passes through Milla and deals no damage:

https://user-images.githubusercontent.com/110129024/181647083-af312ac1-6d2e-4e95-adbc-00d454d882e0.mp4

https://user-images.githubusercontent.com/110129024/181647100-10c7a5b2-89b9-4b36-92b3-a77e16a1e477.mp4

**Comment by whitelilydragon** [comment]
This has been a longstanding accuracy issue with SMA, honestly. However, now that so many things are programmed better than they were, with the game's first public release, I've revisited this issue. And I had an easy time addressing it!

Milla can now block bullets from:

Turretus
Shark Torpedo
Axle Turret

And she can properly deflect projectiles from:

DNA Cannon
RNA Cannon
Bullfrag

Here are some clips of these behaviors in action! I will make sure that Milla's shields can do all of these things with any future enemies I add to the game, as well!

https://user-images.githubusercontent.com/23007238/182011953-299fed9a-419b-48aa-86ce-1ceae60d3142.mov
https://user-images.githubusercontent.com/23007238/182011955-ead211e6-8e60-4703-8ae2-7e891dd1811f.mov

Thank you for reporting!
