### ISSUE TITLE
[1.1.0.5] obj_platform_ver Error on some maps

### ISSUE THREAD

**Issue by TheKitBoi** [whitelilydragon/ShangMuArchitect#282]
![image](https://user-images.githubusercontent.com/84044666/185723377-e6d4e538-57fd-4e1b-878c-e946ff9d73e2.png)

**Comment by whitelilydragon** [comment]
I was able to fix this by changing how the create event handles detection of floating platform tiles! This fix should be in the upcoming rolling build.

Now, in the case of older maps that placed floating platforms on the now-defunct FOF tile layer, the game will place a fresh new tile in its place, and leave the original floating platform tile on Layer 2 alone.

While this does mean you'll have to go back and remove the excess tiles in older map files, it's absolutely better than older maps not being able to load at all!

![Screenshot 2022-8-20 7-6-11-0](https://user-images.githubusercontent.com/23007238/185743106-e64f0b6d-3117-4b1e-8ebd-4ac646cf3e5a.png)

Thank you for reporting!
