### ISSUE TITLE
[1.1.0.7] Items Failed to load or act like a tile caused from some 2021 maps

### ISSUE THREAD

**Issue by TheKitBoi** [whitelilydragon/ShangMuArchitect#283]
heres an example with No Fun Allowed.map

https://user-images.githubusercontent.com/84044666/187222422-4d2c9949-ed1a-4aca-8471-4e2483588a92.mp4

example 2 but the 1up life works

https://user-images.githubusercontent.com/84044666/187222595-f4650fcd-d7fc-466e-b1f1-0da13a7d0e96.mp4

example 3 with the level editor

https://user-images.githubusercontent.com/84044666/187222994-cda470be-4534-469e-904f-14bffa2b0478.mp4

**Comment by whitelilydragon** [comment]
The game has changed dramatically since its 2021 builds. Compatibility with them has broken to an extent that users with maps that old will need to update them manually. I am not concerned with automating any of this while I still have to finish the game, I'm sorry.

**Comment by TheKitBoi** [comment]
I know a fix
it file missing an obj_depth on any lvl_objects_number
so I have to manually add them individually
