### ISSUE TITLE
(Spade) Your second horizontal dash in a row gives you dragon boost levels of speed

### ISSUE THREAD

**Issue by TreyLina** [whitelilydragon/ShangMuArchitect#289]
First level is bike boost speed (which is already pushing it balance wise), second level is dragon boost speed.

No wonder he feels so slippery sometimes! But the new toys he'll get later should make up for removing it, in the end.

**Comment by whitelilydragon** [comment]
As per the latest rolling build, this issue has been fixed! I apologize for taking so long to address the issue.

I was able to fix it by diminishing the dash's speed parameter, with each dash, until Spade lands again, or falls into water, or grabs onto a hangbar/ladder!

This, in tandem with tying the dash to his stamina bar, still allows him to get two to three dashes per jump, if not four or more wherever crystals are present. (Putting his dash nearly on par with the skill ceiling for Lilac's dragon boost.) The new fix simply addresses the ways it can be cheesed further beyond that intention, as you suggested.

Thank you for reporting!
