### ISSUE TITLE
[1.17.6.7.21] [Major] Milla's Supershieldburst

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#29]
Supershieldbursting causes Milla to be pushed through various tiles

https://cdn.discordapp.com/attachments/744727129123455006/747551533213679656/Just_Milla_things.mp4

**Comment by whitelilydragon** [comment]
Fixed the issue by simply disabling knockback while at other compass directions. (Because super shield-bursting while on loops should declip you from slopes, anyway.)

https://cdn.discordapp.com/attachments/739994967186997329/753114776644747284/2020-09-09_00-48-19.mov
