### ISSUE TITLE
(Spade) Various Dual Crash bugs

### ISSUE THREAD

**Issue by TreyLina** [whitelilydragon/ShangMuArchitect#290]
- [ ] If you hold a directional button or touch a ceiling while using dual crash underwater, cards come out but the attack animation stops playing.

- [ ] His grunt plays constantly whenever you hold special, when it should only be at initial activation.

- [ ] Sinking into ceilings with it, potentially causing deaths. Probably to do with dual crash interaction underwater? Video example.

https://user-images.githubusercontent.com/5502946/208335202-b9b3ac44-9e86-4db1-9322-56c540e36604.mp4

**Comment by whitelilydragon** [comment]
As of the latest rolling build, all of these have been fixed! (As well as other issues I caught while fixing these)

-Spade-related bugfixes/improvements
	-Fixed a collision bug, where he could clip through either flat or sloped surface ceilings, by dual-crashing directly against any ceiling. (Which typically results in a crushing death)
	-Fixed accuracy issue where his voice clip for dual-crashing, would play more than once per jump
	-Fixed a bug where his dual crash attack animation wouldn't trigger, while underwater
	-Fixed a bug where Spade's normal cards could finish off the Bouncer too quickly
	-Fixed a bug where Spade's dual crash sound effects could play excessively, while attacking enemies, items, mega items, and even bosses

Thank you for reporting!
