### ISSUE TITLE
Holding Up and Down and then attacking underwater causes Carol to freeze her animations and actions

### ISSUE THREAD

**Issue by jelleejamm** [whitelilydragon/ShangMuArchitect#294]
Doing the dreaded button combo listed in the title underwater freezes Carol's actions and her animations. This can only be fixed by exiting the body of water and pouncing, or by using the S button (Y if your keybinds aren't the default ones).

Doesn't seem to happen with any of her... er, echo fighters? (Carrie and Chiasa)

https://user-images.githubusercontent.com/78974994/233820844-4bc20d7c-8630-4769-8edc-47d630ee6987.mp4

**Comment by whitelilydragon** [comment]
This is something I had thought I fixed, but y'all keyboard users keep finding new ways to break things!

The compromise to fix this was, unfortunately, to disable attacking if the user is holding both Up and Down at the same time. (Which is something SMA tends to do in other contexts, as well; if you attempt to crouch and look up at the same time, the character remains standing instead.)

But, this should be preferable to the character's state freezing. (Particularly nasty in combat scenarios!) Thank you for reporting!
