### ISSUE TITLE
Color palette issues

### ISSUE THREAD

**Issue by jelleejamm** [whitelilydragon/ShangMuArchitect#295]
### 1. The 4th shade used on Lilac's shoe soles doesn't change regardless of the color palette used.
To highlight this better, I created a custom color palette. Say hi to Pinklac!
![Pinklac in the flesh.](https://user-images.githubusercontent.com/78974994/233942718-41e84f48-6c83-4f7e-a6ee-0dc9e8cd3883.png)

Anyway, in the footage below, I demonstrate this exact issue.
![Video.](https://user-images.githubusercontent.com/78974994/233943403-6ee88624-4898-4042-a31b-a84aa661ce60.mp4)

Comparing the color palette to the actual shot in-game, there is clearly something wrong.
![Color palette or something](https://user-images.githubusercontent.com/78974994/233944843-fecee171-67f2-44e4-95bd-35ff2c79be7f.png)
(I noticed that in the default palette, the color in-game and the one from the palette are off by 02 hex in the blue value, so that might have something to do with it? Although this is purely speculation since I don't know how color palettes are handled.)

### 2. Some of the frames from Carol's High Kick don't change colors when using other color palettes.
Again, pretty similar issue to Lilac. This time I used a built-in color palette instead.
![Video.](https://user-images.githubusercontent.com/78974994/233946772-9912d4b9-8c85-42d1-a95f-e2bd25b27820.mp4)
...Yeah. No idea how this even happens.

### 3. Even more color palette hell!
Guess what? While writing this, I found even MORE color palette issues!
I'll just list them off in images for simplicity.

![Carrie](https://user-images.githubusercontent.com/78974994/233949800-076ae054-8420-481c-8ed7-356615f01e03.png)
![Spade](https://user-images.githubusercontent.com/78974994/233950901-88b56375-1a15-431a-ae96-4d0743fc0284.png)

Milla and Chiasa don't seem to have any issues, and I haven't tested Carol's bike at all.

**Comment by whitelilydragon** [comment]
These issues have been known for 3 years or so, particularly in Lilac's case. As the only programmer for this game, stuck between the project and a full-time housekeeping job at a local hospital, I have not had time to give SMA Lilac's "dirty" sprites a clean up pass. (Some of the frames are using the "redundant" colors you see on the palette row.)

It's not that I don't think this issue matters, it's just between coding the enemies, bosses, campaign hubs, cut-scene system, the editor, three more playable characters than originally planned, the NPC system with its ever-increasing complexity, new terrain sprites and coding sloped tiles collisions by hand, making the stages and hubs, optimizing the game- this has fallen under the rug of "I wish I could go back and this fix this, but what is time?".

So, for now, I will not close this issue, but leave it here as a plea for potential volunteers. If anyone with Game Maker experience would like to help out with the smaller issues in SMA, I have a working key for Studio 1.4 that I can provide all volunteers! (Its DRM was disabled in the final update for 1.4.9999)

Until I can go part-time at my job, (Hopefully next month!) it is impossible to set aside the hours needed to clean up every playable characters' sprites.

Even as I type this, I'm busy optimizing RAM usage to resolve an issue with the collision mask array system, which has finally hit a wall- I can't add any new (unique) terrain masks to the game until I've fixed this; it is panic-worthy critical.

**Comment by whitelilydragon** [comment]
It has been close to a year, and it appears no external help is coming, so I am closing this issue for now.

At the time of this writing, I still don't have the time to perform a cleanup pass of the various sprites that need them. (I've been so busy with supporting localizations, for instance!)

If anyone else sees this closed issue and would like to volunteer some time, it would be greatly appreciated! But for now, we have much higher priorities to tackle first.
