### ISSUE TITLE
[1.1.5.6 Rolling Build] Scenes Pipes from the Sewers tileset wasn't been cropped properly

### ISSUE THREAD

**Issue by 23LIEF** [whitelilydragon/ShangMuArchitect#296]
It's possible to notice the pink background from the spritesheet.

![image](https://user-images.githubusercontent.com/89137194/235329590-6ef05c1e-a9aa-4829-a66d-df3d634e23a4.png)

**Comment by whitelilydragon** [comment]
Oh, whoops! This should be fixed once another build has been posted, thank you for catching this!
