### ISSUE TITLE
[1-17-6-7-3][Major] An vertical array of diagonal bouncepads launch a character in the wrong direction.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#3]
![Bouncepad](https://user-images.githubusercontent.com/7067769/90375146-d6098e00-e074-11ea-8d5f-f0b16f4eb271.gif)

With the setup as seen on the GIF. It is seen that bouncepads don't launch a character in the right direction. It seems to only happen with the North-West direction of bouncepads.

**Comment by whitelilydragon** [comment]
I think I've fixed the issue! It was a logical oversight in how the item interaction scripts were handling springs:

![GIF](https://user-images.githubusercontent.com/23007238/91432753-30061280-e830-11ea-90b7-fc5f65a171ee.gif)
