### ISSUE TITLE
[1.17.6.7.21] [Major] Milla get's crushed when fluttering into a ceiling with a ladder

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#30]
Utilizing Flutter or a Supershieldburst to gain height can get you stuck or crushed into latter when it's in a ceiling (also makes Milla warp to a different spot)
 https://cdn.discordapp.com/attachments/744727129123455006/747551523810050178/Ladders_make_Milla_die.mp4

**Comment by Deckardsmegson** [comment]
Additional Video sources

https://cdn.discordapp.com/attachments/739994967186997329/752180157845995592/Ladder_ceilings_are_kill.mp4
https://cdn.discordapp.com/attachments/739994967186997329/752180977769644062/Flooter.mp4

**Comment by whitelilydragon** [comment]
It's a general issue with collisions, which I think I may have fixed for an upcoming build! If there's still more issues with this, please make a new ticket. Thank you for reporting!
