### ISSUE TITLE
[1-17-6-7-23][Major] Crash when using Wood Shield and getting petals from crystals.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#32]
![image](https://user-images.githubusercontent.com/7067769/92813375-5cd63000-f3c1-11ea-902b-9b6d5c4b8017.png)

Seems to be very hard to replicate. Might be related to bouncepads where it happened. I'm setting this to major because of the crash.

**Comment by whitelilydragon** [comment]
This crash was related to how petals and gems interact with other item tiles. Basically, they're still scanning for item tiles to land on, as long as they have gravity, so they're also attempting to scan the spring tile's alternate animation for slope-collision data- and not finding any, so it crashes!

So, I've disabled interacting with item tiles at all, for all variants of the petals and gems objects. Each petal and gem scanning for item tiles created an unnecessary performance tax, anyway! Thank you for reporting, this was a very obscure problem I would've never found myself!
