### ISSUE TITLE
[1.17.6.7.23] [Major] Earth Shield can cause crystals to fly off -> Crash

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#35]
Having an Earth shield, but failing to collect crystals causes them to fly off and cause an Error or Crash

https://cdn.discordapp.com/attachments/739994967186997329/753753054830002256/CrystalYEET.mp4

**Comment by whitelilydragon** [comment]
I've potentially fixed the problem by never allowing petals *and* crystals from escaping the player as they follow them. Basically, once they realize they're within range of the player, they "lock-onto" the player, and keep chasing the player even when they're out of range, all while still gradually increasing their own following speed, until they catch-up to the player.

As a nice side effect of this, players can longer get frustrated by gems and petals losing track of them *bricked*

This now works for all collectable objects related to petals and gems. Thank you for reporting, this is a *very* obscure problem! Please create a new ticket if this problem persists, or your blood turns into peanut oil *bricked*
