### ISSUE TITLE
[1.17.6.7.23] [Minor] Floor-overFloor

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#36]
Placing a Floor-over-Floor tile on top of / near a ladder causes random warping, zipping, clipping and otherwise odd behaviour.
https://cdn.discordapp.com/attachments/739994967186997329/753726025397174432/Floor_over_Floor_tiles_are_weird.mp4

**Comment by whitelilydragon** [comment]
This issue has been fixed, now! Not only that, but clipping onto ladders, as well as standing on ladders, overrides/cancels interactions with moving platforms.

The problem tile in question has also been moved to the slope layer- where it should have been in the first place *bricked*
