### ISSUE TITLE
[1.17.6.7.23] [Minor] Getting Crushed into a ceiling while on a Hangbar causes 2 Deaths

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#37]
Title.description

https://cdn.discordapp.com/attachments/739994967186997329/753662656594051073/DOUBLEDEATH.mp4

Bottom Text

**Comment by whitelilydragon** [comment]
This issue has been fixed as a result of introducing a cooldown timer for collisions with FOF tiles! If you've touched a ceiling, or are currently interacting with ladders, FOF tile collisions are completely disabled.

Now, you gently fall off of a ceiling if you touch it, while standing on a moving platform. Thank you for reporting!
