### ISSUE TITLE
[1.17.6.7.xx] [Suggestion] Turning Tiles

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#38]
Having the ability to turn tiles in 90° intervals would open up a ton more customizability

https://cdn.discordapp.com/attachments/739994967186997329/753712664189861928/1f1b19b7ea15c5789ee5abb1bae95975.png

**Comment by whitelilydragon** [comment]
I have decided to include all suggestions/wishlists in the readme on the "Code" tab, (This is the first page you see when you open the issue tracker) so I will add suggestions to the document, with each ticket received, then close the ticket.

https://github.com/whitelilydragon/ShangMuArchitect/blob/master/README.md

For now, it's just basic volume control while I'm getting the game into its release candidate phase. I will leave suggestion tickets alone after 1.0, and only update/close them when the suggest has A) been implemented, or B) can't be implemented.
