### ISSUE TITLE
[1.17.6.7.23] [Minor] Invisible hitbox of death (See my stage as a reference)

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#39]
On my stage, if you happen to get into the corner shown in the video, you take constant damage, until you die or manage to escape.

https://cdn.discordapp.com/attachments/739994967186997329/753753852783755324/What_the_heck_wall.mp4

https://cdn.discordapp.com/attachments/739994967186997329/753756527193620551/Millas_Funhouse.map

**Comment by whitelilydragon** [comment]
As we discussed earlier, this was a bug with the DNA Cannon that I've currently fixed! (Still refining the DNA Cannon's logic, so that it executes its code only at the times it should.) You will see this fix in the next beta build.

Thank you for reporting!
