### ISSUE TITLE
[1-17-6-7-3][Improvement] As a player "Do you want a save" when using OPEN.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#4]
If somebody made chances in the level and they try to OPEN another one, game doesn't warn that progress/changes made in the level will go to waste.

**Comment by whitelilydragon** [comment]
There's no real time to program additional GUI menus, especially not one that precedes opening stages; I don't remember enough of the UI code to do that yet.

However, I'm able to make a halfway compromise:

![Screenshot 2020-8-29 21-33-55-0](https://user-images.githubusercontent.com/23007238/91649206-6cf42400-ea3f-11ea-86c8-5c0e591c1012.png)

Thank you for the suggestion! I'll provide a more elegant solution in later updates to the game
