### ISSUE TITLE
[1-17-6-7-25][Minor] You can walk on the DNA beam

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#41]
Shoutouts to Treya for the original clip!
https://clips.twitch.tv/FaithfulPhilanthropicHyenaBCouch

You can walk on the DNA-Cannon's beam (if you have protection).
https://cdn.discordapp.com/attachments/739994967186997329/755901759251152946/Solid_DNA_HNGGHHH.mp4

**Comment by whitelilydragon** [comment]
As far as I can tell, I've fixed the DNA Cannon so that its conditional checks ignore scanning for damage, if the player is either invincible, or has entered a victory state. Please make a new ticket if the problem persists in a new form! Thank you for reporting!
