### ISSUE TITLE
[1-17-6-7-27][Major] Lilac can uppercut into collision underwater and possibly get crushed

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#44]
https://cdn.discordapp.com/attachments/739994967186997329/756286505470656572/Uppercut_too_stronk.mp4

If you uppercut underwater into spikes above you, you zip through them.

**Comment by whitelilydragon** [comment]
This seems to be a general collision issue with Lilac's uppercut, it's just that being underwater makes it that much more obvious. I've fixed the issue with stricter gravity speed resets, during the attack's launching phase, if a ceiling has been touched.

I didn't realize Lilac's uppercut was still causing issues, thank you for reporting!
