### ISSUE TITLE
[1-17-6-7-27+][Very Minor] Setting up controls switches the resolution after confirmation

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#45]
This problem seems to only occur once on each new version of a new build. Setting up the controls in the options menu changes the resolution to what is the next highest option available, after confirming the controls and pretting "Okay".

**Comment by whitelilydragon** [comment]
We think the issue has been fixed, as of the current build. A 30-frame lock on inputs has been put in place so the engine can't potentially get the previous controller bindings confused with the new ones, during the transition to the options menu. (Scootles' theory.)

Please create a new ticket if the issue persists, thank you for reporting!
