### ISSUE TITLE
[1-17-6-7-27][Major?] Player preserves invincibility flower effect after restart

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#46]
If the player obtains invincibility from an invincibility flower and restarts the level, the invincibility timer is not set to 0 and instead continues.

**Comment by whitelilydragon** [comment]
I've fixed it by having a hard clearing of all variables at the start of each room; no conditional checks in place.

Thank you for reporting! I thought I had fully patched that one out, but I didn't catch this loophole!
