### ISSUE TITLE
[1-17-6-7-27][Minor] Getting sent to the Titlescreen immediately

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#47]
https://cdn.discordapp.com/attachments/739994967186997329/756655971119661108/Dumb_button_input.mp4
https://cdn.discordapp.com/attachments/739994967186997329/756656420929273906/level_3_speedrun.mp4

If you happen to press the "back" button during the screen transition of entering a stage and then either beating said stage or quitting, you get sent to the Main menu.

**Comment by whitelilydragon** [comment]
This has been fixed with a 30 frame lock on action button inputs, at the start of the room. Thank you for reporting!
