### ISSUE TITLE
[1-17-6-7-3][Critical] Placing a Loop Exit object in the level and the SAVING, crashes the game.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#5]
![Loop Exit](https://user-images.githubusercontent.com/7067769/90376127-46fd7580-e076-11ea-83f9-1f37611ceb0d.png)

Pretty self explanatory.

**Comment by whitelilydragon** [comment]
This has not only since been fixed, the loop exit object is now more robust! It won't lose track of slope tiles as you repeatedly place the object over a loop's pieces.

Thank you for reporting! This completely slipped under my nose
