### ISSUE TITLE
[1-17-6-7-30][C] Blade Orbiters Hitboxes (Hurtboxes?)

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#50]
https://cdn.discordapp.com/attachments/739994967186997329/759198434489794560/Blade_Orbiter_thingies.mp4

The Blade Orbiter as shown in the video should be able to hit you with it's blade right after it draws them. Standing in between the swords should also be possible (unless it's too complicated).

**Comment by whitelilydragon** [comment]
I originally thought it would be too complicated to fix this, but nah, the blade orbiter just needed multi-staged hitboxes! This means it looks for a player's X/Y position within a point ellipse while its swords are rotating, **then** it starts searching for the player's X/Y position within two 16-pixel point rectangles.

I still need to adjust how wide of a margin there is to avoid damage from beneath the blade orbiter, but now, his behavior should be much more accurate!

https://user-images.githubusercontent.com/23007238/102968140-50ce3400-44c1-11eb-82ed-0aacb09bb3bc.mov

Thank you for reporting!
