### ISSUE TITLE
[1-17-6-7-32][C] DNA-Cannons are not grounded 

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#51]
DNA-Cannons do not properly attach to the floor, regardless of where you put them. This also causes them to (sometimes) not properly mount to Pendulums, Pinwheels and other floating Platforms.

https://cdn.discordapp.com/attachments/739994967186997329/760589045243576381/e07951830675a5d698c39c60d3b3f9f3.png

https://cdn.discordapp.com/attachments/739994967186997329/760592909417971722/Cannon_FEET.mp4

https://cdn.discordapp.com/attachments/739994967186997329/760593737037905970/You_had_1_job.mp4

**Comment by whitelilydragon** [comment]
I am not seeing any evidence of this in current builds, so if there are specific conditions that cause them to raise up after falling onto a surface, please make a new ticket with the specifics of the issue.
