### ISSUE TITLE
[1-17-6-7-32][C] Spring Physics (Momentum) get nullified from midair (double)jumping

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#52]
https://cdn.discordapp.com/attachments/739994967186997329/760613724565405716/Spring-momentum_dum.mp4

As seen in this example, jumping midair after jumping on a spring causes all of the momentum of the spring to vanish.
The example below shows the intended behaviour.

https://cdn.discordapp.com/attachments/739994967186997329/760613803255136296/Spring_momentum_Yea.mp4

https://cdn.discordapp.com/attachments/739994967186997329/760623461307121734/Springy_springs.mp4

Milla has a special quirk with her horizontal burst that it also nullifies the momentum.

https://cdn.discordapp.com/attachments/739994967186997329/760623500532383754/Mill_qyoob_powerful.mp4

**Comment by whitelilydragon** [comment]
Turns out, the issue was simply that the variable jump height code was never specifically told to only trigger during the jump animation. Specifying when it should trigger fixed this issue!

Thank you for reporting!
