### ISSUE TITLE
[1-17-6-7-3][Major] Momentum from bouncepads is conserved after slamming a wall.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#6]
![Conservation](https://user-images.githubusercontent.com/7067769/90376624-10742a80-e077-11ea-8b61-ffc8da46f012.gif)

Character gets catapulted after vaulting a vertical wall when under the effects of the bounce pad, which looks really uncanny. Character should go straight up in those situation, not dash forward.

**Comment by NBlastMax** [comment]
Bumping it up to Major. Because of this bug, there is a way to soft-lock yourself in specific situations

**Comment by NBlastMax** [comment]
![BounceBlock](https://user-images.githubusercontent.com/7067769/90951235-45a6c100-e459-11ea-9c4e-1da1cc83eb7e.gif)

**Comment by whitelilydragon** [comment]
There's now a variable in place to disable locked horizontal movement, if you've touched a wall! This should fix the issue, thank you for reporting!

![GIF](https://user-images.githubusercontent.com/23007238/91440427-9729c400-e83c-11ea-83a1-d95f429fb18e.gif)
