### ISSUE TITLE
[1.0.0.0] [Minor] Carol can pounce through springs

### ISSUE THREAD

**Issue by ElNachoCR** [whitelilydragon/ShangMuArchitect#63]
Both gold and blue springs show this behaviour. Groundpouncing at the springs also makes her clip through them

https://cdn.discordapp.com/attachments/739994967186997329/788606990334165022/2020-12-15_21-18-18.mp4

**Comment by whitelilydragon** [comment]
As far as I can tell, this happens regardless of her pouncing state, as long as she's pouncing into a wall of springs. I'll be looking at this issue after work; this is kind of a big deal.

**Comment by whitelilydragon** [comment]
Update: I fixed it!

As far as I could tell, the game was taking at least one or two frames too long to inform Carol's code that she has touched a spring, so her leaping movement code was careening right through the spring tile! :stuck_out_tongue: She can't do this anymore.

Thank you for reporting!
