### ISSUE TITLE
[1.0.0.1] [A] Game crashes if you do a soft reset on a level with a bike spawner

### ISSUE THREAD

**Issue by ElNachoCR** [whitelilydragon/ShangMuArchitect#65]
This is an odd one to explain, but it is very easy to replicate. If you make al evel that uses the bike spawner it loads fine, However if you were to hit F2 to soft restart the game, the level becomes permanently broken and it will crash the game no matter how many times you relaunch it.

https://cdn.discordapp.com/attachments/739994967186997329/789677661014327326/F2BikeSpawner__Crash.mp4

A workaround I found was simply loading a different level that does not use the bike spawner, and then the level with the bike spawner can be loaded again without crashing. I have no idea what could be happening, all I know is F2 + Bike Spawner level temporarily bricks any and all levels that use that spawner until you load one with a different spawner.

**Comment by whitelilydragon** [comment]
This one was painful! It's as simple as the script for switching Carol's Bike's "skin" not having one variable that Carol's non-bike script does initialize! This would even cause the character switching keys to crash the game, if Carol's Bike was picked before Carol's normal form was!

Thank you for reporting, it's so easy to miss stuff like this!
