### ISSUE TITLE
[1.0.0.1][Minor] Lilacs uppercut into loops causes her to clip into floors and causes death

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#69]
This seems to be an issue regarding the height of which the loop tile resets your position after performing an uppercut into a loop tile that is close to the floor.
https://user-images.githubusercontent.com/69774625/102950002-ec63a280-44c9-11eb-8f18-5b1ff51ce5a7.mp4

**Comment by whitelilydragon** [comment]
Oopsie! I was able to fix this by having a broader conditional check on disabling the uppercut, when coming into contact with a ceiling. Basically, Lilac was only checking if she should stop attacking and fall, upon contact with a sloped ceiling, if she was already at a certain frame in the attack, which allowed for this to happen with shallower ceilings. This is a behavior she already had for flat surface tiles, but not sloped surface tiles; who knows what I was thinking at the time *bricked*

Thank you for reporting!
