### ISSUE TITLE
[1-17-6-7-3][Major] Characters gets teleported when moving up under the slope tiles.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#7]
![UnderSlope](https://user-images.githubusercontent.com/7067769/90377021-a8721400-e077-11ea-8224-293a16cbc285.gif)

This works on all sorts of slopes, not just showcased here. This happens on all characters.

**Comment by whitelilydragon** [comment]
This issue has been fixed in most recent builds, so I'm closing this ticket now. Please open a new ticket if our newest double-sided tile system misbehaves!

Thank you for reporting!
