### ISSUE TITLE
[1.0.0.2][Minor] Auto-layer mode continues "feeling out" the layer underneath the tile menu

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#71]
While the tile menu is open, if the layer mode is set to "Auto", it continues detecting the layer on placed tiles behind the tile menu. This often results in picking a "flat" tile but then placing it on a scene layer by mistake. Because a decoration tile was under the cursor beneath the tile menu at the spot the flat tile was clicked.

https://user-images.githubusercontent.com/38583427/103138254-68800500-46d9-11eb-98b0-1a07a3ebb705.mp4

Pay attention to the layer on the right as the tiles are clicked in the menu.

**Comment by whitelilydragon** [comment]
This was a super simple fix! All I had to do was add one more condition to allowing the automatic tile scanners to run their code. For as long as you're not currently using a popup menu of any kind, it won't change what tile layer is currently selected underneath the cursor anymore.

Thank you for reporting! This was not an issue to let go amiss.
