### ISSUE TITLE
[1.0.0.2][Minor] If multiple pendulums/carousels are too close, an enemy placed on one of them will "hop" between them sporadically

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#74]
Sometimes the enemy will even fall off entirely, and I'm not sure what causes it?

https://user-images.githubusercontent.com/38583427/103138420-2b1c7700-46db-11eb-9158-27a00833e77d.mp4

**Comment by whitelilydragon** [comment]
This is a consequence of how enemy recollecting works! If your cursor is hovering over an enemy's "ghost", or rather, their spawn point, they will respawn at that point.

So, if your cursor is hovering over that enemy's ghost, while there's no platform to support them, they will just fall to their doom :smiling_imp:

So, my solution to this, was to simply disable "recapturing" the enemy object from their "ghost", so long as they're attached to a moving platform. (They will still reset to their original positions while the game is saving, though. But the rotating platforms also reset their angular rotations upon saving the game, so they still shouldn't fall off.)

It's assumed that, if you're really needing to interact with/copy/delete an enemy, you will simply grab them from some point along the carasol or pendulum, where they'll be easy to find, and in the event that they do somehow fall off of those platforms, their capture state will end, and you can recapture them from their ghost's position again!

Thank you for reporting!
