### ISSUE TITLE
[1.0.0.2][Minor] Crash caused by placing a tile whilst holding E to erase tiles at the same time

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#75]
Since placing and erasing tiles at the same time makes no logical sense, I've marked it as minor.

https://user-images.githubusercontent.com/38583427/103138438-5acb7f00-46db-11eb-8cfa-628dcdfddc53.mp4

![E error](https://user-images.githubusercontent.com/38583427/103136295-d7ecf900-46c7-11eb-8f8f-8f76d5b39658.png)

**Comment by whitelilydragon** [comment]
Oh wow! This is catastrophically bad, I'm glad you caught it. After enough fiddling, I was able to fully lock the use of the "delete" key/button from activating while the game was also clicking/dragging tiles around.

This fortunately didn't affect the mouse at all, so I didn't need additional checks for that; you can simultaneously click the right mouse button and it won't do anything while the left mouse button is being held

Thank you for reporting!
