### ISSUE TITLE
[1.1.x.x][Suggestion] Lilac's Uppercut on Sloped Surfaces and Ceilings

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#76]
https://cdn.discordapp.com/attachments/739994967186997329/792164900247699466/2020-12-25_18-00-18.mov

As seen in the Video, Lilac is able to Uppercut from these surfaces, albeit with lackluster results in FP. As of right now, you can not do that in SMA at all and if it were to be implemented correctly, it could prove to be a nice feature for future revisions of SMA

**Comment by whitelilydragon** [comment]
I've included this on the to-do list for the main page! Thank you for the suggestion!
