### ISSUE TITLE
[1.0.0.2][Minor] Millas Supershieldburst leaves particles and let's you move in a different direction

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#77]
In the video you can see how Milla can change her direction immediately after firing a SSB. This is not intended and also leaves off with an improper animation.
https://user-images.githubusercontent.com/69774625/103143512-e2cf7a00-4717-11eb-98ee-47b5f4e84736.mp4

**Comment by whitelilydragon** [comment]
The animations are still correct, it's that shield's particle animations aren't maintaining an assigned direction after the shield burst. This is a known issue in the past and has proved difficult to fix, so I will close the ticket when I have a solution.

**Comment by whitelilydragon** [comment]
I was able to fix this with a new check that provides directional locking for 20 frames, after initializing either shield burst attack!

https://user-images.githubusercontent.com/23007238/107146209-a4cb9580-6914-11eb-944d-ca66ea2fba99.mov
