### ISSUE TITLE
[1-17-6-7-3][Normal] Cube can be summoned during idle animation

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#8]
![magic dog](https://user-images.githubusercontent.com/69790793/90411104-1f9bae00-e060-11ea-991d-fbd122610d5c.gif)

majik dog

**Comment by whitelilydragon** [comment]
This issue, among others, has been fixed recently, so I'm closing the ticket now. Thanks for reporting!
