### ISSUE TITLE
[1-0-0-6][Normal] Using Restart while having a shield, restarts you with that shield.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#81]
Get a shield and a checkpoint in a level, then Pause and hit RESTART.

You will respawn the the shield you had.

**Comment by whitelilydragon** [comment]
This was another easy fix! I had the game reset the shield's active state upon entering the title screen or menu rooms, but not when restarting a stage- whoops

Thank you for catching this!
