### ISSUE TITLE
[1-0-0-6][Critical] Placing Water Switch element in place where there is no button (or there is but player didn't realize they didn't hit the hitbox) crashes the game.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#86]
![Zrzut ekranu 2021-01-03 130143sCREEN2](https://user-images.githubusercontent.com/7067769/103480208-48380080-4dd3-11eb-8650-df96d0e7241c.png)

Try to "miss" when placing Water Switch element on the button and you might get such Crash report.

**Comment by whitelilydragon** [comment]
This was a pretty easy fix! The object just wasn't double-checking if the tile existed before attempting to read its X/Y coordinates and asset ID *bricked*

Thank you for reporting! I'm glad you caught this
