### ISSUE TITLE
[1-0-0-6] Floating Platform 5 has completely inaccurate collision boxes

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#87]
Not only standing on it is wonky, but **it doesn't have "sides" so Carol cannot wall-jump off them like in original Trap Hideout**, making Floating Platform 5 unusable.

![Screen3](https://user-images.githubusercontent.com/7067769/103480248-7cabbc80-4dd3-11eb-88dc-ce5c27879574.png)

**Comment by whitelilydragon** [comment]
As mentioned in a previously closed ticket, this has been fixed! I had simply forgotten about the issue, among all of the other things I was fixing.

Thank you for reporting!
