### ISSUE TITLE
[1.0.0.6][Minor] User Manual irregularities and suggestions

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#89]
Here's a couple of oddities that I found reading the User Manual that I think could be clarified:

_Table of contents:_ "Play mode" -> How to play as Lilac, Carol and Milla (with the control guide, this could be much simpler to set up)
"Accessibility Bar" -> Add a section where you explain all the features of the accessibility bar in the pause menu

_-Crystal flowers drop "several" crystal shards each._ -> should read **"Seven"** Crystals
_-Crates drop several crystal shards each._ -> Same as above, **"Seven"** Crystals

-Brass targets appear in both "Hit the Targets!" and "Reach the Target!" game modes. In the former, hitting them reduces the player's target count by 1, while in the latter, hitting a "bronze" target clears the player's entire target count. -> should read **"Brass"** Target but could also be rephrased as "... while in the latter, hitting a brass target clears the stage".

_-Key cards open locked doors, via key card terminals placed nearby them. The player can carry as many key cards as they like!_ -> "Players can only use one Card per terminal" 

_-Shields_ -> Clarify that **all shields protect the player from damage** twice or three times as Milla, as well as providing certain immunities and then List off the various additional effects.

_-Gold springs are useful for strongly bouncing the player in any of eight directions"," and "as a consequence", must be used with more care. Experiment with them, discern what works best._ -> "consequently" is more concise and "," aren't needed when you say "and" (Nitpick)

_-Break the Targets!

Simply place only brass targets to set your stage to "Break the Targets!" mode._ -> This is confusing, as there isn't really a "Setting" so to speak. Adding a disclaimer that you **shouldn't place any** Tin targets should clear this.

_-Saving_ -> Add disclaimer to **"SAVE OFTEN"**

_-Once your stage is finished, or you want to save your progress as you work, click the "hamburger icon" on the sidebar, and choose either Save or Save As from the file dialogue menu._ -> In the manual, the icon is highlighted in red but it's still a bit hard to see. Maybe try using a contrasting color. Suggestion: "To save, click the icon in top left corner of the HUD that looks like a burger..."

_Spawners_ -> Very important tile, consider putting them into the main section of items, rather than in the advanced sections.

If anyone else reads this, feel free to add more suggestions below

**Comment by whitelilydragon** [comment]
I'm closing this ticket, because with the most recent version of the manual, I have addressed all of these problems and then some.

For future reference, I would appreciate more questions about the manual being handled through the private developer Discord; this Github issue tracker is strictly for software bugs, not nitpicking non-gameplay related content.
