### ISSUE TITLE
Crash when hitting Play in Editor 1.0.0.7

### ISSUE THREAD

**Issue by N00neIsHere** [whitelilydragon/ShangMuArchitect#90]
___________________________________________
Objects  in map, Firespitter, Brass Target, Floor, Downward Slope Steep 1, Camera Boundary Left, Camera Boundary Bottom. Game Crashed when clicking Play in the editor.

############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_game_logic:

Tile does not exist.
at gml_Object_obj_game_logic_Draw_0
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_obj_game_logic_Draw_0 (line -1)

**Comment by whitelilydragon** [comment]
I finally figured out why it was crashing, as I stated on our dev Discord for the game:

>For some reason, the horizontal moving platform clings to the player, even after they exit play test mode in the editor, so if you respawn the player- no matter where you are in the map, they will respawn onto that platform. But usually that platform no longer exists while editing, so the game crashes.

I placed some safety checks on the IDs of floating platform tiles, and the editor itself now clears the player's variables related to FOF tile IDs and asset IDs.

Thank you for reporting this! It's a genuine Class A bug, good find.
