### ISSUE TITLE
Deleting Loop-De-Loop Spawner leaves invisible platforms sometimes 1.0.0.7

### ISSUE THREAD

**Issue by N00neIsHere** [whitelilydragon/ShangMuArchitect#91]
I try to recreate the gltich with a second loop but it doesn't occur a second time. Video shows what this means.

https://user-images.githubusercontent.com/77096912/103873186-718bb180-509d-11eb-8d24-3fb9b28b8d5b.mp4

**Comment by NBlastMax** [comment]
I did notice a similar issue, but I couldn't reproduce it. It wasn't a loop, but a moving platform tiles. This might be connected, but unfortunately I have no more clues about the nature of such occurence.

**Comment by whitelilydragon** [comment]
I believe this was an issue with how the controller object's tiles were being checked for, so I fixed that, and I'm not discovering any more leftover tiles with the loop controller! Please open a new ticket if this persists, or other objects are presenting similar issues.

Thank you for reporting!
