### ISSUE TITLE
[1.0.0.9][Feature Regression] Milla can no longer utilize infinite flight with Super Shield Bursts

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#92]
As seen in the video, Milla is no longer able to fly infinitely via utilizing properly timed fluttering and SSBs. This is likely due to the new Stamina implementation, where gems increase it. Hitting the floor or spring instantly restores Stamina however 

https://user-images.githubusercontent.com/69774625/104624693-2ae91900-5694-11eb-99dc-444d689ad4e1.mp4

**Comment by whitelilydragon** [comment]
Fortunately, this was the result of the stamina bar's own variable not getting reset, upon activating the super shield burst! So, now, Milla's stamina bar is refreshed upon using the super shield burst, allowing her to flutterblock infinitely again.

Thank you for reporting!
