### ISSUE TITLE
[1.0.0.9][C] Lilacs Dragonboost on sloped Surface tiles causes zipping

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#94]
As seen in the video below, Lilacs Dragonboost causes some Issues on sloped Surface tiles, depending on which direction you move in and on which angle you boost from.

https://cdn.discordapp.com/attachments/739994967186997329/799255735837655070/Zip_Zoom_Lilac_dies.mp4

**Comment by whitelilydragon** [comment]
This was a surprisingly simple oversight in the code! The checks in place for preventing further changes in direction, after initializing the boost, were still active even during the boost itself, and I added a ground check for downward directional changes, too, just to be on the safe side!

Thank you for reporting!
