### ISSUE TITLE
[1.0.0.9][D] Lilac can cancel Dragonboost with a jump/cyclone while on a slope

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#95]
While Lilac is on a sloped surface, you can cancel the Dragonboost during the windup. This is not possible in FP1

https://cdn.discordapp.com/attachments/739994967186997329/799379014924894238/2021-01-14_21-45-24.mp4

**Comment by whitelilydragon** [comment]
I was able to address this by performing a check for the dragon boost, before the entire code block for activating the cyclone is allowed to execute!

Thank you for reporting. I wouldn't have caught this at all.
