### ISSUE TITLE
[1.0.0.9][Minor] Pressing all action buttons as Lilac causes her to display all of her animations

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#96]
If you press all of the Action buttons (Attack, Jump, Special) at the same time in succession, it will cause Lilac to display all of her animations. This is best replicated by currently binding all of the Action Buttons to a single Button, though it can be replicated by pressing all 3 buttons at the same time.

https://user-images.githubusercontent.com/69774625/104812909-e1204000-5805-11eb-8ba9-ebdfe1190374.mp4

https://user-images.githubusercontent.com/69774625/104812894-bb933680-5805-11eb-8faa-43ae26ee3b37.mp4

**Comment by whitelilydragon** [comment]
I was able to fix this issue simply by not allowing multiple actions to be assigned to a single key/button! The input setup will swap out conflicting button mappings if they are detected, just like in Freedom Planet 1- can't believe I never thought to check this.

Thank you for reporting!
